"""Extra data entries for English analysis pages (8 exams)."""


# ============ 沈河区 ============
def shenhe():
    return {
    "district": "沈河区",
    "exam_name": "2026年九年级英语学科教学数据采集试题",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分，考试时间90分钟），听力口语单独考试。阅读理解20题40分占笔试44.4%，加上阅读还原与阅读表达共58分，阅读能力占比<strong>64.4%</strong>。题号从Q1起编，无听力偏移。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"校园社团招新海报(英语角/美术/体育)","theme":"校园生活·活动","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("海报","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"时间信息提取","location":"English Corner: Every Wednesday→B"},
            {"no":"Q2","type":"细节理解","ability":"地点信息提取","location":"Art Club: Art Room→B"},
            {"no":"Q3","type":"细节理解","ability":"数量计算","location":"Sports Club: basketball+badminton=2→A"},
            {"no":"Q4","type":"文体判断","ability":"文本类型识别","location":"全文→海报(poster)→B"},
         ]},
        {"id":"B","genre":"说明文","topic":"植物的\"智慧\"——植物间化学信号传递","theme":"科学探索·植物","difficulty":"★★☆","cls":"",
         "tags":[("说明文","blue"),("科学","orange"),("植物","green")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"关键信息提取","location":"第2段: two U.S. scientists→A"},
            {"no":"Q6","type":"细节理解","ability":"时间信息提取","location":"第2段: About 36 hours later→C"},
            {"no":"Q7","type":"词义猜测","ability":"上下文推断","location":"damage=Hurt→C"},
            {"no":"Q8","type":"标题选择","ability":"主旨概括","location":"Plants Are Smarter Than We Think→D"},
         ]},
        {"id":"C","genre":"议论文","topic":"A New Pool, A New You——勇敢尝试新事物","theme":"个人成长·勇气","difficulty":"★★☆","cls":"success",
         "tags":[("议论文","orange"),("成长","purple"),("勇气","green")],
         "questions":[
            {"no":"Q9","type":"作者态度","ability":"态度判断","location":"全文Positive→B"},
            {"no":"Q10","type":"细节理解","ability":"论据提取","location":"worked in 12 countries→B"},
            {"no":"Q11","type":"代词指代","ability":"指代推断","location":"that=Fearing failure→C"},
            {"no":"Q12","type":"主旨大意","ability":"中心思想","location":"Trying new things helps us grow→A"},
         ]},
        {"id":"D","genre":"说明文","topic":"科学零食——如何健康地吃零食","theme":"健康生活·饮食","difficulty":"★★☆","cls":"warning",
         "tags":[("说明文","blue"),("健康","green"),("饮食","orange")],
         "questions":[
            {"no":"Q13","type":"段落大意","ability":"段落归纳","location":"Many people snack in unhealthy way→B"},
            {"no":"Q14","type":"细节理解","ability":"因果关系","location":"plan snack time→prevent weight gain→C"},
            {"no":"Q15","type":"细节理解","ability":"优点描述","location":"fruit+nuts→keep full 2-3 hours→B"},
            {"no":"Q16","type":"细节理解","ability":"建议归纳","location":"Choose what to eat before we start→D"},
         ]},
    ],
    "restore": {
        "topic": "保护视力——健康用眼习惯",
        "structure": "问题引入→习惯建议→饮食建议→总结号召",
        "slots": [
            ("17","段首","后文developing healthy habits→引出重要性","C"),
            ("18","段中","前文not watch TV too long→补充用眼建议","E"),
            ("19","段首","后文vitamins in them→引出水果蔬菜","B"),
            ("20","段尾","总结→keep eyesight sharp","A"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "Growing My Money——兄弟俩学习投资理财",
        "emotion_line": "父亲交任务→哥哥卖无人机获利→弟弟跟投+货币投资→父亲教导理财→反思教育缺失",
        "theme": "学会管理金钱，否则金钱将管理你",
        "questions": [
            {"no":"Q21","type":"固定搭配","pos":"动词","answer":"B. spend","clue":"spend...on sth"},
            {"no":"Q22","type":"语境推理","pos":"名词","answer":"C. money","clue":"before you have the money"},
            {"no":"Q23","type":"语境推理","pos":"动词","answer":"A. resold","clue":"bought drones and resold online"},
            {"no":"Q24","type":"语境推理","pos":"动词","answer":"D. made","clue":"made a profit of £260"},
            {"no":"Q25","type":"语境推理","pos":"代词","answer":"A. my","clue":"I spent some of my profit"},
            {"no":"Q26","type":"固定搭配","pos":"动词短语","answer":"A. follow","clue":"follow the example of"},
            {"no":"Q27","type":"语境推理","pos":"名词","answer":"C. brother's","clue":"invested in Hywel's drone business"},
            {"no":"Q28","type":"逻辑连词","pos":"副词","answer":"D. Therefore","clue":"best at money→因此制定计划"},
            {"no":"Q29","type":"语境推理","pos":"形容词","answer":"B. top","clue":"a top secret"},
            {"no":"Q30","type":"语境推理","pos":"动词短语","answer":"C. ends up","clue":"money ends up managing you"},
        ],
        "word_types": [("动词/动词短语","4","40%"),("名词","3","30%"),("形容词","1","10%"),("代词","1","10%"),("副词","1","10%")],
    },
    "grammar_topic": "尼罗河的馈赠——古埃及文明与尼罗河",
    "grammar_theme": "历史文明·地理",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"词性转换(名→形)","answer":"African","clue":"Africa→African修饰countries"},
        {"no":"Q32","type":"无提示·虚词","point":"连词","answer":"but","clue":"desert转折→but brought life"},
        {"no":"Q33","type":"无提示·虚词","point":"冠词","answer":"the","clue":"the soil along its banks特指"},
        {"no":"Q34","type":"有提示·词形变化","point":"一般过去时","answer":"grew","clue":"ancient Egyptians grew"},
        {"no":"Q35","type":"有提示·词形变化","point":"序数词","answer":"third","clue":"the first/second/third"},
        {"no":"Q36","type":"有提示·词形变化","point":"固定搭配","answer":"addition","clue":"In addition固定短语"},
        {"no":"Q37","type":"无提示·虚词","point":"介词","answer":"with","clue":"provided them with"},
        {"no":"Q38","type":"有提示·词形变化","point":"名词复数","answer":"homes","clue":"build homes"},
        {"no":"Q39","type":"有提示·词形变化","point":"被动语态","answer":"were built","clue":"cities were built near it"},
        {"no":"Q40","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to carry","clue":"traveled on it to carry"},
    ],
    "grammar_stats": [
        ("被动语态(过去时)","1","高"),("一般过去时","1","高"),("词性转换(名→形)","1","高"),
        ("非谓语(to do)","1","高"),("序数词","1","中"),("名词复数","1","中"),
        ("固定搭配(in addition)","1","中"),("冠词(the)","1","中"),("连词(but)","1","中"),("介词(with)","1","中"),
    ],
    "reading_expr_topic": "纸质日历的美好——Alpha世代的\"日历情结\"",
    "reading_expr_genre": "议论文",
    "reading_expr_tone": "温馨·怀旧",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"What does the writer compare the calendar to?","answer":"The desktop buddy / book of days."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"When does the writer begin to put the new calendar?","answer":"On January 1."},
        {"no":"Q43","score":"2分","type":"推理归纳","question":"What effect do the pictures on paper calendars have?","answer":"They take people on a journey in imagination and help forget tiring work."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Do you agree some old things are too good to let go? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"新闻报道","topic":"Beautiful Handicrafts校园手工作品展","genre":"新闻报道","word_count":"80-100",
        "requirements":["参加人员","活动内容并简介一两个手工作品","活动意义"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q3,Q5,Q6,Q10,Q13,Q14,Q15,Q16","10","20分"),
        ("推理判断(Inference)","Q9,Q11","2","4分"),("主旨大意(Main Idea)","Q12","1","2分"),
        ("词义猜测(Word Meaning)","Q7","1","2分"),("标题选择(Best Title)","Q8","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","校园社团招新海报","校园生活·活动"),("B篇·阅读选择","植物间化学信号传递","科学探索·植物"),
        ("C篇·阅读选择","勇敢尝试新事物","个人成长·勇气"),("D篇·阅读选择","科学健康地吃零食","健康生活·饮食"),
        ("阅读还原","保护视力与健康用眼","健康生活·视力"),("完形填空","兄弟俩学习投资理财","财商教育·家庭"),
        ("语篇填空","尼罗河与古埃及文明","历史文明·地理"),("阅读与表达","纸质日历的美好","生活方式·怀旧"),
        ("书面表达","校园手工作品展报道","校园活动·新闻"),
    ],
    "dna": [
        {"title":"观察一 · 选材贴近学生生活——校园/健康/理财/成长四大主线",
         "body":"A篇校园社团、C篇勇敢尝试、D篇健康零食、完形篇理财教育，紧扣学生日常。语篇填空以尼罗河古埃及为载体考查语法。<strong>备考启示→</strong>关注校园、健康、成长类话题。"},
        {"title":"观察二 · 细节理解题占比超60%——基础能力是拿分关键",
         "body":"16道阅读选择中细节理解10题(62.5%)。Q14考因果关系，Q15考优点归纳，设题紧扣文本。<strong>备考启示→</strong>训练快速定位+精确理解能力。"},
        {"title":"观察三 · 语篇填空以历史文化为载体——语法覆盖10大考点",
         "body":"尼罗河话题涵盖：词性转换(African)、连词(but)、冠词(the)、过去时(grew)、序数词(third)、固定搭配(addition)、介词(with)、名词复数(homes)、被动语态(were built)、非谓语(to carry)。<strong>备考启示→</strong>重点掌握被动语态和固定搭配。"},
        {"title":"观察四 · 完形填空考查财商话题——固定搭配和语境推理并重",
         "body":"投资理财话题新颖，spend...on/follow the example/ends up doing等固定搭配占40%。<strong>备考启示→</strong>积累常见动词短语搭配。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(海报)</strong>：3分钟速读，信息在表格中直接定位</li><li><strong>B篇(科学)</strong>：关注实验步骤和结论</li><li><strong>C篇(议论文)</strong>：找论点+论据，代词指代回原文</li><li><strong>D篇(健康)</strong>：每段一个建议，按段落对应题目</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=新闻报道，要点=人员+内容+意义，时态=过去时为主</li><li>描述1-2个具体手工作品(paper-cutting/clay model)展现细节</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(7题)：词性转换/过去时/被动/序数词</li><li>无提示(3题)：but(转折)/the(特指)/with(固定搭配)</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：通读把握\"父亲出题→兄弟投资→收获感悟\"主线</li><li>还原：先做最确定的空(Q19水果蔬菜→B)，再排除</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 于洪区 ============
def yuhong():
    return {
    "district": "于洪区",
    "exam_name": "2025-2026学年度下学期第一次模拟测试",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分，考试时间90分钟），无听力。阅读能力占比<strong>64.4%</strong>。语篇填空以敦煌洞窟壁画数字化为话题，传统文化与现代科技融合。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"Spring Sports Day学校春季运动会通知","theme":"校园生活·体育","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("通知","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"时间信息提取","location":"Afternoon Matches: 13:30→C"},
            {"no":"Q2","type":"细节理解","ability":"规则提取","location":"Tips: Keep playground clean→C"},
            {"no":"Q3","type":"推理判断","ability":"信息推断","location":"Winners get medal+notebook→B"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"school noticeboard→D"},
         ]},
        {"id":"B","genre":"记叙文","topic":"外国人学中文的经历与方法","theme":"跨文化交际·语言","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("语言学习","green"),("中国文化","purple")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"因果关系","location":"interested in Chinese culture→C"},
            {"no":"Q6","type":"词义猜测","ability":"上下文推断","location":"arduous=困难的→A"},
            {"no":"Q7","type":"细节理解","ability":"方法归纳","location":"thinking through conversations→B"},
            {"no":"Q8","type":"推理判断","ability":"作者暗示","location":"never easy+still learning→C"},
         ]},
        {"id":"C","genre":"说明文","topic":"如何写电影评论——实用写作技巧","theme":"学习方法·写作","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("写作技巧","green"),("电影","orange")],
         "questions":[
            {"no":"Q9","type":"细节理解","ability":"数量计算","location":"4个tips→B"},
            {"no":"Q10","type":"细节理解","ability":"注意事项","location":"Never give spoilers→B"},
            {"no":"Q11","type":"段落大意","ability":"段落归纳","location":"other details→A"},
            {"no":"Q12","type":"标题选择","ability":"主旨概括","location":"Ways to Write a Good Movie Review→C"},
         ]},
        {"id":"D","genre":"记叙文","topic":"济宁单亲妈妈与自闭症儿子——陌生人的善意","theme":"社会温情·善良","difficulty":"★★★","cls":"warning",
         "tags":[("记叙文","orange"),("善良","purple"),("社会","green")],
         "questions":[
            {"no":"Q13","type":"细节理解","ability":"因果关系","location":"tied son→protect→B"},
            {"no":"Q14","type":"细节理解","ability":"细节提取","location":"don't have money→B"},
            {"no":"Q15","type":"人物评价","ability":"性格概括","location":"kind+strong→D"},
            {"no":"Q16","type":"主旨大意","ability":"文章启示","location":"shows love and hope→D"},
         ]},
    ],
    "restore": {
        "topic": "电子设备对学生的三大危害及应对",
        "structure": "引出话题→危害一(眼睛)→危害二(学习)→危害三(交际)→解决方案",
        "slots": [
            ("17","段首","后文Staring at screen→eye strain→坏眼睛","D"),
            ("18","段尾","前文play games in class→错过知识","B"),
            ("19","段中","前文don't talk to parents→破坏关系","A"),
            ("20","段中","前文deal with problems→合理使用","C"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "老木匠教年轻人打磨——耐心与成功的关系",
        "emotion_line": "年轻人着急→简单打磨被拒→不耐烦再试→反思后仔细打磨→终于成功→领悟耐心真谛",
        "theme": "成功不仅需要技能，更需要耐心",
        "questions": [
            {"no":"Q21","type":"固定搭配","pos":"动词短语","answer":"A. learn from","clue":"came to learn from him"},
            {"no":"Q22","type":"语境推理","pos":"副词","answer":"B. faster","clue":"make furniture faster"},
            {"no":"Q23","type":"语境推理","pos":"形容词","answer":"D. smooth","clue":"sanded→光滑"},
            {"no":"Q24","type":"语境推理","pos":"形容词","answer":"D. easy","clue":"thought it was easy"},
            {"no":"Q25","type":"语境推理","pos":"动词","answer":"C. touched","clue":"touched the board检查"},
            {"no":"Q26","type":"语境推理","pos":"动词","answer":"A. shook","clue":"shook his head"},
            {"no":"Q27","type":"语境推理","pos":"副词","answer":"D. carefully","clue":"不再着急+仔细打磨"},
            {"no":"Q28","type":"语境推理","pos":"名词","answer":"B. skill","clue":"not only skill but patience"},
            {"no":"Q29","type":"语境推理","pos":"形容词","answer":"C. patient","clue":"more boring→more patient"},
            {"no":"Q30","type":"语境推理","pos":"名词","answer":"B. spirit","clue":"true spirit of carpentry"},
        ],
        "word_types": [("形容词","4","40%"),("名词","2","20%"),("动词","2","20%"),("副词","2","20%")],
    },
    "grammar_topic": "数字技术让古代艺术\"活\"起来——清明上河图+敦煌壁画",
    "grammar_theme": "传统文化·科技",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"动名词","answer":"seeing","clue":"amazed by seeing"},
        {"no":"Q32","type":"有提示·词形变化","point":"词性转换(名→形)","answer":"famous","clue":"the famous painting"},
        {"no":"Q33","type":"有提示·词形变化","point":"词性转换(动→名)","answer":"artist","clue":"Chinese artist"},
        {"no":"Q34","type":"无提示·虚词","point":"冠词","answer":"a","clue":"a lot of"},
        {"no":"Q35","type":"有提示·词形变化","point":"名词复数","answer":"Farmers","clue":"Farmers work in fields"},
        {"no":"Q36","type":"有提示·词形变化","point":"词性转换(形→名)","answer":"business","clue":"do business"},
        {"no":"Q37","type":"无提示·虚词","point":"连词","answer":"and","clue":"trees and across water"},
        {"no":"Q38","type":"有提示·词形变化","point":"名词复数","answer":"ideas","clue":"express their ideas"},
        {"no":"Q39","type":"无提示·虚词","point":"介词","answer":"as","clue":"such as animation"},
        {"no":"Q40","type":"有提示·词形变化","point":"被动语态","answer":"are filled","clue":"Caves are filled with"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("动名词","1","高"),("词性转换(名→形)","1","高"),
        ("名词复数","2","高"),("词性转换(动→名)","1","中"),("词性转换(形→名)","1","中"),
        ("冠词(a)","1","中"),("连词(and)","1","中"),("介词(as)","1","中"),
    ],
    "reading_expr_topic": "减肥成功的故事——改变不良生活习惯",
    "reading_expr_genre": "记叙文",
    "reading_expr_tone": "励志·实用",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"What did the doctor say to the writer?","answer":"My heavy weight was bad for my health."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"How did the writer lose his weight?","answer":"He just changed his bad daily habits."},
        {"no":"Q43","score":"2分","type":"细节提取","question":"Which is the most important way?","answer":"Be patient and keep doing these rules all the time."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Do you have any suggestion of being healthy? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"书信","topic":"回复外国好友Eric——介绍自己的业余活动","genre":"书信/邮件","word_count":"80-100",
        "requirements":["感谢信任","介绍自己的业余活动","愿意继续提供帮助"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q5,Q7,Q9,Q10,Q13,Q14","8","16分"),
        ("推理判断(Inference)","Q3,Q8,Q15","3","6分"),("主旨大意(Main Idea)","Q16","1","2分"),
        ("词义猜测(Word Meaning)","Q6","1","2分"),("标题选择(Best Title)","Q12","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("段落大意(Paragraph)","Q11","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","学校春季运动会通知","校园生活·体育"),("B篇·阅读选择","外国人学中文的经历","跨文化交际·语言"),
        ("C篇·阅读选择","如何写电影评论","学习方法·写作"),("D篇·阅读选择","单亲妈妈与自闭症儿子的温情","社会温情·善良"),
        ("阅读还原","电子设备对学生的危害","健康生活·科技"),("完形填空","老木匠教徒弟打磨的故事","品质修养·耐心"),
        ("语篇填空","数字技术让古代艺术活起来","传统文化·科技"),("阅读与表达","减肥成功——改变生活习惯","健康生活·习惯"),
        ("书面表达","介绍业余活动的回信","跨文化交际·日常"),
    ],
    "dna": [
        {"title":"观察一 · 中国传统文化元素突出——清明上河图+敦煌壁画双话题",
         "body":"语篇填空以数字技术复活古代艺术为话题，与\"中国故事+科技创新\"选材趋势高度吻合。<strong>备考启示→</strong>积累文化遗产相关词汇。"},
        {"title":"观察二 · 完形填空记叙文+人生哲理——形容词占40%",
         "body":"老木匠教徒弟打磨的故事，情感线从\"着急→失败→反思→成功→领悟\"。形容词题需通过情感变化推断。<strong>备考启示→</strong>注意情感转折词(but/however/finally)。"},
        {"title":"观察三 · D篇社会温情选材——济宁单亲妈妈故事触动人心",
         "body":"D篇讲述卖凉面的单亲妈妈与自闭症儿子的温情故事。人物评价题(kind and strong)是中考高频题型。<strong>备考启示→</strong>训练人物性格词汇+证据定位能力。"},
        {"title":"观察四 · 还原题结构清晰——First/Second/Third标志明显",
         "body":"电子设备话题的\"总分总\"结构，每段首句有明确标志(First/Second/Third)。<strong>备考启示→</strong>还原题先识别文章结构，再利用段首标志词定位。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(通知)</strong>：3分钟速读，Tips/Time/Place直接定位</li><li><strong>B篇(学中文)</strong>：按段落对应方法(听/说/读/写)</li><li><strong>C篇(写作技巧)</strong>：4个tips按段落一一对应题目</li><li><strong>D篇(温情)</strong>：抓人物关系和情感变化</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=回信，要点=感谢+介绍活动+愿意帮助，时态=一般现在时</li><li>介绍2-3个业余活动并简述理由</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(7题)：动名词(seeing)/词性转换/名词复数/被动(are filled)</li><li>无提示(3题)：冠词(a)/连词(and)/介词(as)</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：打磨木板隐喻人生，形容词按情绪变化选</li><li>还原：First/Second/Third标志明显，先做Q17最确定</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 皇姑区 ============
def huanggu():
    return {
    "district": "皇姑区",
    "exam_name": "2025-2026学年(下)初中毕业年级阶段性质量监测",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分，考试时间90分钟），无听力。阅读理解20题40分占44.4%，加上阅读还原与阅读表达共58分，阅读能力占比<strong>64.4%</strong>。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"骆驼科普知识卡片(Camel Fact Sheet)","theme":"科学·动物","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("科普","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"生活习性提取","location":"social animals walk in groups→B"},
            {"no":"Q2","type":"细节理解","ability":"数据提取","location":"Weight:300-1000kg→D"},
            {"no":"Q3","type":"推理判断","ability":"信息推断","location":"reflects sun+keeps cool/warm→special→C"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"fact sheet→science magazine→D"},
         ]},
        {"id":"B","genre":"记叙文","topic":"害羞女孩找到自己的声音","theme":"个人成长·自信","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("成长","purple"),("自信","green")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"情感理解","location":"miserable and lost→C"},
            {"no":"Q6","type":"细节理解","ability":"人物关系","location":"sister said Do something→B"},
            {"no":"Q7","type":"细节理解","ability":"行为提取","location":"share my ideas→B"},
            {"no":"Q8","type":"推理判断","ability":"性格变化推断","location":"finding strength→braver→C"},
         ]},
        {"id":"C","genre":"说明文","topic":"太阳的科学知识(Facts about the Sun)","theme":"科学探索·天文","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("天文","orange"),("科学","green")],
         "questions":[
            {"no":"Q9","type":"细节理解","ability":"因果关系","location":"gravity keeps planets moving→A"},
            {"no":"Q10","type":"细节理解","ability":"数据提取","location":"one full orbit 230 million years→D"},
            {"no":"Q11","type":"推理判断","ability":"作者态度推断","location":"only 8 minutes→quite easy→B"},
            {"no":"Q12","type":"标题选择","ability":"主旨概括","location":"Facts about the Sun→A"},
         ]},
        {"id":"D","genre":"说明文","topic":"微塑料的危害与防护","theme":"环保·健康","difficulty":"★★★","cls":"warning",
         "tags":[("说明文","blue"),("环保","green"),("健康","orange")],
         "questions":[
            {"no":"Q13","type":"细节理解","ability":"因果关系","location":"they're everywhere→hard to deal with→B"},
            {"no":"Q14","type":"细节理解","ability":"危害归纳","location":"hurt cells and endocrine system→D"},
            {"no":"Q15","type":"词义猜测","ability":"上下文推断","location":"release=let out→A"},
            {"no":"Q16","type":"写作目的","ability":"作者意图","location":"warn readers about microplastics→C"},
         ]},
    ],
    "restore": {
        "topic": "牛奶实验——科学发现中的犯错精神",
        "structure": "引出科学家→母亲的反应→实验探索→收获教训",
        "slots": [
            ("17","段首","引出famous scientist→后文his mother","E"),
            ("18","段中","前文what a great mess→补充I have never seen such a puddle","C"),
            ("19","段尾","前文carry without dropping→What a wonderful lesson","A"),
            ("20","段尾","前文mistakes are chances→总结don't need to be afraid","D"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "Kevin的纸条——家庭中被忽视的孩子",
        "emotion_line": "兄弟争吵→Kevin哭泣→母亲传纸条→Kevin吐露心声→母亲回应→和解",
        "theme": "家人之间的爱需要用心表达和关注",
        "questions": [
            {"no":"Q21","type":"语境推理","pos":"名词","answer":"D. problem","clue":"didn't think it was a big problem"},
            {"no":"Q22","type":"语境推理","pos":"动词","answer":"B. crying","clue":"heard Kevin crying"},
            {"no":"Q23","type":"语境推理","pos":"副词","answer":"A. Still","clue":"I tried again. Still nothing"},
            {"no":"Q24","type":"语境推理","pos":"动词","answer":"B. sat","clue":"sat on the floor outside"},
            {"no":"Q25","type":"语境推理","pos":"形容词","answer":"C. youngest","clue":"not youngest nor oldest"},
            {"no":"Q26","type":"语境推理","pos":"形容词","answer":"A. good","clue":"good at basketball"},
            {"no":"Q27","type":"语境推理","pos":"动词","answer":"C. notice","clue":"never around to notice me"},
            {"no":"Q28","type":"语境推理","pos":"形容词","answer":"D. sorry","clue":"feeling sorry for him"},
            {"no":"Q29","type":"语境推理","pos":"动词短语","answer":"A. came out","clue":"note came out from under door"},
            {"no":"Q30","type":"语境推理","pos":"动词","answer":"C. smile","clue":"smile and say Write it on paper"},
        ],
        "word_types": [("动词/动词短语","4","40%"),("形容词","3","30%"),("名词","1","10%"),("副词","2","20%")],
    },
    "grammar_topic": "幸运的秘密——为什么有些人总是那么幸运",
    "grammar_theme": "心理学·生活态度",
    "grammar": [
        {"no":"Q31","type":"无提示·虚词","point":"代词所有格","answer":"their","clue":"watched their lives"},
        {"no":"Q32","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to study","clue":"experiment to study"},
        {"no":"Q33","type":"有提示·词形变化","point":"一般过去时","answer":"asked","clue":"gave...and asked"},
        {"no":"Q34","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"secretly","clue":"secretly placed"},
        {"no":"Q35","type":"有提示·词形变化","point":"词性转换(v→n)","answer":"researcher","clue":"Tell the researcher"},
        {"no":"Q36","type":"有提示·词形变化","point":"被动语态","answer":"was missed","clue":"it was missed by unlucky people"},
        {"no":"Q37","type":"有提示·词形变化","point":"比较级","answer":"more nervous","clue":"more nervous than lucky people"},
        {"no":"Q38","type":"无提示·虚词","point":"介词","answer":"of","clue":"in front of them"},
        {"no":"Q39","type":"无提示·虚词","point":"连词","answer":"and","clue":"open to new experiences and break"},
        {"no":"Q40","type":"无提示·虚词","point":"冠词","answer":"a","clue":"as a lucky person"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("一般过去时","1","高"),("比较级","1","高"),
        ("词性转换(adj→adv)","1","高"),("词性转换(v→n)","1","高"),
        ("非谓语(to do)","1","中"),("代词所有格","1","中"),
        ("介词(of)","1","中"),("连词(and)","1","中"),("冠词(a)","1","中"),
    ],
    "reading_expr_topic": "男孩与小狗Doobie——桥上等待的忠犬",
    "reading_expr_genre": "记叙文",
    "reading_expr_tone": "温馨·怀旧",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"What does the author think the best thing about Camp Caesar was?","answer":"A public swimming pool."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"Where did Doobie wait for the author?","answer":"On a/the bridge."},
        {"no":"Q43","score":"2分","type":"细节提取","question":"How did Doobie drive the author's loneliness away?","answer":"With his doggie kisses."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"What do you think of \"sharing love and joy\"? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"书信","topic":"回复James——分享一顿特别的饭","genre":"书信/邮件","word_count":"80-100",
        "requirements":["何时、何地、和谁吃的","特别的原因及期间发生的事","你的感受"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q5,Q6,Q7,Q9,Q10,Q13,Q14","9","18分"),
        ("推理判断(Inference)","Q3,Q8,Q11","3","6分"),("主旨大意(Main Idea)","","0","0分"),
        ("词义猜测(Word Meaning)","Q15","1","2分"),("标题选择(Best Title)","Q12","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("写作目的(Purpose)","Q16","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","骆驼科普知识卡片","科学·动物"),("B篇·阅读选择","害羞女孩找到自信","个人成长·自信"),
        ("C篇·阅读选择","太阳的科学知识","科学探索·天文"),("D篇·阅读选择","微塑料的危害与防护","环保·健康"),
        ("阅读还原","牛奶实验与犯错精神","学习方法·科学"),("完形填空","Kevin的纸条——家庭沟通","家庭关爱·沟通"),
        ("语篇填空","幸运的秘密——生活态度","心理学·态度"),("阅读与表达","男孩与忠犬Doobie的温情","友谊·动物"),
        ("书面表达","回信分享一顿特别的饭","日常生活·饮食"),
    ],
    "dna": [
        {"title":"观察一 · 科学话题占比高——动物/天文/微塑料三篇说明文",
         "body":"A篇骆驼科普、C篇太阳知识、D篇微塑料危害，科学类占阅读选择3/4。语篇填空以心理学实验为载体。<strong>备考启示→</strong>加强科学类说明文阅读训练。"},
        {"title":"观察二 · 完形填空情感线索强——家庭沟通主题考查语境推理",
         "body":"Kevin纸条故事从\"争吵→哭泣→传纸条→吐露心声→和解\"一气呵成，全部10题靠情感线推理。<strong>备考启示→</strong>通读全文把握情感走向再做题。"},
        {"title":"观察三 · 语篇填空覆盖核心语法——被动语态+比较级+词性转换",
         "body":"10题涵盖：代词所有格(their)/不定式(to study)/过去时(asked)/adj→adv(secretly)/v→n(researcher)/被动(was missed)/比较级(more nervous)/介词(of)/连词(and)/冠词(a)。<strong>备考启示→</strong>词性转换(adj↔adv, v↔n)是高频考点。"},
        {"title":"观察四 · 阅读还原以科学故事为载体——犯错精神贴合中考价值观",
         "body":"\"牛奶实验\"故事传递\"mistakes are chances to learn\"的成长理念，与中考\"积极向上\"选材导向一致。<strong>备考启示→</strong>关注科学家成长故事类语篇。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(科普卡)</strong>：3分钟，信息在图表中直接定位</li><li><strong>B篇(记叙文)</strong>：按时间线找情感转折点</li><li><strong>C篇(天文)</strong>：数据题直接定位段落</li><li><strong>D篇(微塑料)</strong>：每段一个要点，Q15词义猜测回原句</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=回信，要点=时间地点人物+特别原因+感受</li><li>时态=过去时为主，描述事件+感受用1-2个亮点句</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(6题)：过去时/被动/比较级/词性转换×2/不定式</li><li>无提示(4题)：their/of/and/a，均为常见虚词</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：紧扣\"Kevin被忽视→传纸条→和解\"情感线</li><li>还原：Q17科学家引出→E最确定，再做其余</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 铁西区 ============
def tiexi():
    return {
    "district": "铁西区",
    "exam_name": "九年级阶段性测试",
    "has_listening": True,
    "skeleton_note": "本卷为<strong>听力+笔试卷</strong>（65题120分，考试时间100分钟），听力20题30分+笔试45题90分。笔试中阅读理解20题40分占笔试44.4%，加上阅读还原与阅读表达共58分，阅读能力占笔试<strong>64.4%</strong>。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"DIY灭蚊瓶制作说明","theme":"科学实验·生活","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("实验","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"步骤顺序","location":"put sugar+yeast in warm water→C(water first implied)→实际sugar先"},
            {"no":"Q2","type":"推理判断","ability":"原因推断","location":"CO2 attracts mosquitoes→follow CO2→D"},
            {"no":"Q3","type":"主旨大意","ability":"主旨概括","location":"How to catch mosquitoes→C"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"science experiment→B"},
         ]},
        {"id":"B","genre":"记叙文","topic":"日记体——篮球失败转向游泳成功","theme":"个人成长·挫折","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("成长","purple"),("日记","green")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"因果关系","location":"coach said not tall enough→failed→C"},
            {"no":"Q6","type":"词义猜测","ability":"上下文推断","location":"a big deal=an important thing→C"},
            {"no":"Q7","type":"细节理解","ability":"目的理解","location":"swam to take mind off things→B"},
            {"no":"Q8","type":"推理判断","ability":"主旨推断","location":"failure→new chances→A"},
         ]},
        {"id":"C","genre":"说明文","topic":"攀登珠穆朗玛峰的中国故事","theme":"中国故事·探险","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("中国故事","purple"),("探险","orange")],
         "questions":[
            {"no":"Q9","type":"细节理解","ability":"细节提取","location":"terrible conditions→A"},
            {"no":"Q10","type":"细节理解","ability":"方法提取","location":"1975 brought a ladder→C"},
            {"no":"Q11","type":"细节理解","ability":"数量计算","location":"1960+1975+2020=three teams→C"},
            {"no":"Q12","type":"标题选择","ability":"主旨概括","location":"Reaching New Heights→A"},
         ]},
        {"id":"D","genre":"记叙文","topic":"Kai的古琴探索——传统与现代的平衡","theme":"传统文化·音乐","difficulty":"★★★","cls":"warning",
         "tags":[("记叙文","orange"),("传统文化","purple"),("音乐","green")],
         "questions":[
            {"no":"Q13","type":"细节理解","ability":"反应理解","location":"classmates jumped and cheered→B"},
            {"no":"Q14","type":"代词指代","ability":"指代推断","location":"they=Mr Li and Miss Zhou→D"},
            {"no":"Q15","type":"细节理解","ability":"信息归纳","location":"connects people with nature→D"},
            {"no":"Q16","type":"推理判断","ability":"情节预测","location":"balance traditional+modern→B"},
         ]},
    ],
    "restore": {
        "topic": "猫为什么不喜欢水——三大原因",
        "structure": "引出话题→原因一(沙漠祖先)→原因二(湿毛不舒服)→原因三(自洁能力)→例外",
        "slots": [
            ("17","段尾","前文wild cats lived in dry places→water not normal","D"),
            ("18","段中","前文fur becomes heavy→feels uncomfortable and cold","E"),
            ("19","段首","后文excellent self-cleaners→Cats keep themselves clean","A"),
            ("20","段中","前文some cats are the opposite→curious about water","C"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "Tilly Smith与2004年海啸——10岁女孩救百人",
        "emotion_line": "度假→发现异常→回忆老师讲解→警告家人→疏散海滩→海啸来袭→全员生还",
        "theme": "知识的力量——一堂地理课拯救百条生命",
        "questions": [
            {"no":"Q21","type":"语境推理","pos":"动词","answer":"C. noticed","clue":"noticed something strange"},
            {"no":"Q22","type":"语境推理","pos":"动词短语","answer":"B. going out","clue":"waves coming in instead of going out"},
            {"no":"Q23","type":"语境推理","pos":"动词","answer":"D. explained","clue":"teacher had explained"},
            {"no":"Q24","type":"语境推理","pos":"名词","answer":"A. wave","clue":"big wave=tsunami"},
            {"no":"Q25","type":"语境推理","pos":"名词","answer":"A. step","clue":"refused to take a single step"},
            {"no":"Q26","type":"语境推理","pos":"形容词","answer":"B. possible","clue":"tsunami was possible"},
            {"no":"Q27","type":"语境推理","pos":"形容词","answer":"C. scared","clue":"people got scared"},
            {"no":"Q28","type":"语境推理","pos":"副词","answer":"D. thankfully","clue":"thankfully made it to safety"},
            {"no":"Q29","type":"语境推理","pos":"动词","answer":"A. caused","clue":"caused over 200,000 deaths"},
            {"no":"Q30","type":"语境推理","pos":"名词","answer":"C. knowledge","clue":"thanks to knowledge and quick thinking"},
        ],
        "word_types": [("动词/动词短语","4","40%"),("名词","3","30%"),("形容词","2","20%"),("副词","1","10%")],
    },
    "grammar_topic": "春晚武BOT——人形机器人表演中国功夫",
    "grammar_theme": "科技创新·传统文化",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"最高级","answer":"most popular","clue":"one of the most popular"},
        {"no":"Q32","type":"无提示·虚词","point":"连词","answer":"and","clue":"martial artists and they amazed"},
        {"no":"Q33","type":"有提示·词形变化","point":"一般过去时","answer":"performed","clue":"They performed on stage"},
        {"no":"Q34","type":"有提示·词形变化","point":"名词复数","answer":"humans","clue":"worked well with humans"},
        {"no":"Q35","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"easily","clue":"complete moves easily"},
        {"no":"Q36","type":"无提示·虚词","point":"冠词","answer":"a","clue":"not just a fun performance"},
        {"no":"Q37","type":"无提示·虚词","point":"介词","answer":"in","clue":"in a creative way"},
        {"no":"Q38","type":"有提示·词形变化","point":"一般将来时被动","answer":"will be used","clue":"robots will be used in education"},
        {"no":"Q39","type":"有提示·词形变化","point":"代词宾格","answer":"them","clue":"see them in classrooms"},
        {"no":"Q40","type":"有提示·词形变化","point":"固定搭配(would like to do)","answer":"to have","clue":"Would you like to have"},
    ],
    "grammar_stats": [
        ("一般将来时被动","1","高"),("一般过去时","1","高"),("最高级","1","高"),
        ("词性转换(adj→adv)","1","高"),("名词复数","1","高"),
        ("代词宾格","1","中"),("固定搭配(would like to do)","1","中"),
        ("冠词(a)","1","中"),("连词(and)","1","中"),("介词(in)","1","中"),
    ],
    "reading_expr_topic": "同伴压力——如何应对同龄人的影响",
    "reading_expr_genre": "议论文",
    "reading_expr_tone": "理性·指导",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"What pressure does the writer think is a big one for kids?","answer":"Peer pressure."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"Why do some teenagers have to do things like smoking or drinking?","answer":"To avoid being alone."},
        {"no":"Q43","score":"2分","type":"开放性表达","question":"Give one example of 'something else' you could suggest.","answer":"Playing basketball./Reading books./Going hiking...(答案不唯一)"},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Which suggestion is more helpful for you? Why? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"发言稿","topic":"校园生活技能活动——选择最想学的一项技能","genre":"发言稿","word_count":"80-100",
        "requirements":["你最想学的一项技能","选择此项技能的原因","对此次活动的期望"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q5,Q7,Q9,Q10,Q11,Q13,Q15","8","16分"),
        ("推理判断(Inference)","Q2,Q8,Q16","3","6分"),("主旨大意(Main Idea)","Q3","1","2分"),
        ("词义猜测(Word Meaning)","Q6","1","2分"),("标题选择(Best Title)","Q12","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("代词指代(Reference)","Q14","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","DIY灭蚊瓶制作说明","科学实验·生活"),("B篇·阅读选择","篮球失败转向游泳成功","个人成长·挫折"),
        ("C篇·阅读选择","攀登珠穆朗玛峰的中国故事","中国故事·探险"),("D篇·阅读选择","古琴传统与现代的平衡","传统文化·音乐"),
        ("阅读还原","猫为什么不喜欢水","科学·动物"),("完形填空","10岁女孩与2004海啸","知识·勇气"),
        ("语篇填空","春晚武BOT人形机器人","科技创新·传统文化"),("阅读与表达","同伴压力的应对","心理健康·社交"),
        ("书面表达","校园生活技能活动发言稿","校园活动·生活技能"),
    ],
    "dna": [
        {"title":"观察一 · 中国元素突出——珠穆朗玛峰+古琴+春晚武BOT三连",
         "body":"C篇中国攀登珠峰故事、D篇古琴传统与现代的碰撞、语篇填空春晚人形机器人，\"中国故事+传统文化+科技创新\"三大主线贯穿全卷。<strong>备考启示→</strong>积累中国文化和科技相关词汇。"},
        {"title":"观察二 · 完形填空真实事件改编——海啸救人故事考查语境推理",
         "body":"Tilly Smith的真实故事，情节跌宕(发现异常→警告→疏散→生还)，10题全靠情节线推理。<strong>备考启示→</strong>真实事件类完形需抓住时间线和因果链。"},
        {"title":"观察三 · 语篇填空以科技新闻为载体——将来时被动是新考点",
         "body":"春晚武BOT话题新颖，will be used(将来时被动)是近年新增考点。传统考点most popular(最高级)/performed(过去时)/easily(词性转换)同时覆盖。<strong>备考启示→</strong>关注\"一般将来时+被动\"的组合形式。"},
        {"title":"观察四 · D篇开放性结尾——古琴话题设情节预测题",
         "body":"D篇以\"Then, he had an idea...\"结尾，Q16问Kai下一场会怎么做。这类预测题需综合理解Miss Zhou的建议(master rules first, balance traditional+modern)。<strong>备考启示→</strong>开放结尾类需回文找线索。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(实验说明)</strong>：看Steps+How it works直接定位</li><li><strong>B篇(日记)</strong>：2022 vs 2026对比，找情感转折</li><li><strong>C篇(珠峰)</strong>：1960/1975/2020三个时间点对应</li><li><strong>D篇(古琴)</strong>：抓Miss Zhou的建议做Q15-Q16</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=发言稿，要点=选择的技能+原因+期望</li><li>开头Hello everyone!+结尾That's all. Thank you!已给出</li><li>写2-3个选择理由，用First/Second/Third连接</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(7题)：最高级/过去时/名词复数/词性转换/将来时被动/代词宾格/固定搭配</li><li>无提示(3题)：and/a/in，均为高频虚词</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：海啸故事按时间线推进，Q28 thankfully是转折标志</li><li>还原：猫不喜欢水，Q19(自洁)最确定先做</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 苏家屯区 ============
def sujiatun():
    return {
    "district": "苏家屯区",
    "exam_name": "2025-2026学年度下学期九年级学情调研问卷(一)",
    "has_listening": True,
    "skeleton_note": "本卷为<strong>听力+笔试卷</strong>（65题120分，考试时间110分钟），听力20题30分+笔试45题90分。笔试阅读Q21-Q36共16题40分占笔试44.4%，加上阅读还原与阅读表达共58分，阅读能力占笔试<strong>64.4%</strong>。题号从Q21起编（含听力偏移）。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"四款科技礼物推荐(机器人/3D笔/Kindle/智能笔记本)","theme":"科技·消费","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("科技","blue")],
         "questions":[
            {"no":"Q21","type":"细节理解","ability":"价格比较","location":"Miko 3 Robot $249 most expensive→A"},
            {"no":"Q22","type":"细节理解","ability":"原理理解","location":"heats up plastic to create 3D models→D"},
            {"no":"Q23","type":"细节理解","ability":"特点归纳","location":"erase and write again→over and over→C"},
            {"no":"Q24","type":"推理判断","ability":"读者对象","location":"Looking for a gift for your children→parents→B"},
         ]},
        {"id":"B","genre":"说明文","topic":"睡前温水澡改善睡眠质量","theme":"健康生活·睡眠","difficulty":"★★☆","cls":"",
         "tags":[("说明文","blue"),("健康","green"),("睡眠","orange")],
         "questions":[
            {"no":"Q25","type":"细节理解","ability":"功能理解","location":"body clock controls when we fall asleep→C"},
            {"no":"Q26","type":"细节理解","ability":"习惯提取","location":"roommate took hot shower every morning→D"},
            {"no":"Q27","type":"细节理解","ability":"数据提取","location":"15 minutes or so→B"},
            {"no":"Q28","type":"代词指代","ability":"指代推断","location":"this=drop in body temperature→C"},
         ]},
        {"id":"C","genre":"说明文","topic":"校园绿角(Green Corner)的利与弊","theme":"校园生活·环保","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("校园","green"),("环保","orange")],
         "questions":[
            {"no":"Q29","type":"细节理解","ability":"概念定义","location":"small area to grow plants→D"},
            {"no":"Q30","type":"段落大意","ability":"段落归纳","location":"Para 2=advantages→B"},
            {"no":"Q31","type":"细节理解","ability":"问题归纳","location":"forget to water→plants die→C"},
            {"no":"Q32","type":"写作目的","ability":"目的推断","location":"make green corner better→A"},
         ]},
        {"id":"D","genre":"记叙文","topic":"Gavin的舞蹈之夜——从抗拒到热爱","theme":"个人成长·艺术","difficulty":"★★★","cls":"warning",
         "tags":[("记叙文","orange"),("成长","purple"),("艺术","green")],
         "questions":[
            {"no":"Q33","type":"细节理解","ability":"态度判断","location":"walked slowly down stairs→didn't want to go→B"},
            {"no":"Q34","type":"细节理解","ability":"数量计算","location":"ballet/modern/tap/jazz/break/square/tango/waltz+1=D"},
            {"no":"Q35","type":"推理判断","ability":"态度变化","location":"'When can I start?'→interested→A"},
            {"no":"Q36","type":"标题选择","ability":"主旨概括","location":"Gavin's Big Night at the Theater→C"},
         ]},
    ],
    "restore": {
        "topic": "如何成为一个有趣的人——四个建议",
        "structure": "引出话题→学新事物→运动交友→与人交流→学会倾听",
        "slots": [
            ("Q37","段首","前文how can you become interesting→Here are some ways","C"),
            ("Q38","段尾","前文make more friends→It helps you become friendly","E"),
            ("Q39","段中","前文bring different advantages→Different people share ideas","D"),
            ("Q40","段首","后文listening carefully→Learn to be a good listener","A"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "Reggie的沉默日——为聋人设立节日",
        "emotion_line": "Reggie被区别对待→Michael提议→全镇戴耳塞→体会聋人生活→重新认识Reggie",
        "theme": "理解与包容——换位思考才能真正看见他人",
        "questions": [
            {"no":"Q41","type":"语境推理","pos":"副词","answer":"C. unluckily","clue":"unluckily treated differently"},
            {"no":"Q42","type":"语境推理","pos":"动词","answer":"B. understand","clue":"unable to understand them"},
            {"no":"Q43","type":"语境推理","pos":"动词","answer":"B. change","clue":"do something to change the situation"},
            {"no":"Q44","type":"语境推理","pos":"动词","answer":"D. managed","clue":"managed to persuade"},
            {"no":"Q45","type":"语境推理","pos":"名词","answer":"C. festival","clue":"offer one day as a festival"},
            {"no":"Q46","type":"语境推理","pos":"名词","answer":"B. idea","clue":"People liked the idea"},
            {"no":"Q47","type":"语境推理","pos":"形容词","answer":"A. hard","clue":"how hard life was"},
            {"no":"Q48","type":"语境推理","pos":"动词","answer":"D. communicate","clue":"communicate best with everyone"},
            {"no":"Q49","type":"语境推理","pos":"形容词","answer":"D. surprised","clue":"surprised by his intelligence"},
            {"no":"Q50","type":"语境推理","pos":"名词","answer":"A. difference","clue":"the only difference"},
        ],
        "word_types": [("动词","3","30%"),("名词","3","30%"),("形容词","2","20%"),("副词","2","20%")],
    },
    "grammar_topic": "美国博主Jade的北京六日游",
    "grammar_theme": "跨文化交际·中国文化",
    "grammar": [
        {"no":"Q51","type":"无提示·虚词","point":"连词(转折)","answer":"but","clue":"only six days but made good use"},
        {"no":"Q52","type":"有提示·词形变化","point":"被动语态","answer":"were greeted","clue":"they were greeted by the rich history"},
        {"no":"Q53","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"happily","clue":"happily ordered beef"},
        {"no":"Q54","type":"有提示·词形变化","point":"名词复数","answer":"kinds","clue":"So many kinds of sauces"},
        {"no":"Q55","type":"无提示·虚词","point":"冠词","answer":"the","clue":"attend the lantern festival特指"},
        {"no":"Q56","type":"有提示·词形变化","point":"词性转换(n→adj)","answer":"colourful","clue":"colourful lanterns"},
        {"no":"Q57","type":"无提示·虚词","point":"数词","answer":"one","clue":"describe in one word"},
        {"no":"Q58","type":"有提示·词形变化","point":"一般过去时","answer":"left","clue":"adventures left a deep impression"},
        {"no":"Q59","type":"无提示·虚词","point":"介词","answer":"to","clue":"looking forward to experiencing"},
        {"no":"Q60","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to explore","clue":"start learning Chinese to explore"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("一般过去时","1","高"),("词性转换(adj→adv)","1","高"),
        ("名词复数","1","高"),("词性转换(n→adj)","1","高"),
        ("非谓语(to do)","1","中"),("冠词(the)","1","中"),
        ("连词(but)","1","中"),("介词(to)","1","中"),("数词(one)","1","中"),
    ],
    "reading_expr_topic": "\"美国图书管理员\"Nancy的阅读人生",
    "reading_expr_genre": "记叙文",
    "reading_expr_tone": "温馨·励志",
    "reading_expression": [
        {"no":"Q61","score":"2分","type":"细节提取","question":"When did Nancy begin to love books?","answer":"When she was young."},
        {"no":"Q62","score":"2分","type":"细节提取","question":"Where did Nancy meet Miss Whitehead?","answer":"At the public library."},
        {"no":"Q63","score":"2分","type":"因果推理","question":"Why did Nancy become much busier after retiring?","answer":"Because she started a book group."},
        {"no":"Q64","score":"4分","type":"开放性表达","question":"Do you like to join a book group? Why or why not? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"投稿信","topic":"班级才艺展示活动","genre":"投稿信","word_count":"80-100",
        "requirements":["才艺展示活动概况","你的参与过程","感受与收获"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q21,Q22,Q23,Q25,Q26,Q27,Q29,Q31,Q33,Q34","10","20分"),
        ("推理判断(Inference)","Q24,Q28,Q35","3","6分"),("段落大意(Paragraph)","Q30","1","2分"),
        ("标题选择(Best Title)","Q36","1","2分"),("写作目的(Purpose)","Q32","1","2分"),
        ("逻辑衔接(Cohesion)","Q37-Q40","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","四款科技礼物推荐","科技·消费"),("B篇·阅读选择","睡前温水澡改善睡眠","健康生活·睡眠"),
        ("C篇·阅读选择","校园绿角的利与弊","校园生活·环保"),("D篇·阅读选择","Gavin的舞蹈之夜","个人成长·艺术"),
        ("阅读还原","如何成为有趣的人","社交·自我提升"),("完形填空","为聋人设立沉默日","包容·换位思考"),
        ("语篇填空","美国博主的北京六日游","跨文化交际·旅行"),("阅读与表达","Nancy的阅读人生","阅读·职业"),
        ("书面表达","班级才艺展示活动投稿","校园活动·分享"),
    ],
    "dna": [
        {"title":"观察一 · 中国文化体验贯穿全卷——火锅+灯笼节+校园绿角",
         "body":"语篇填空以美国博主Jade北京之旅为载体，涉及火锅、元宵灯笼节，传递\"中国故事\"。C篇校园绿角体现劳动教育。<strong>备考启示→</strong>积累中国美食和节日相关词汇。"},
        {"title":"观察二 · 完形填空社会议题——聋人包容主题考查人文素养",
         "body":"Reggie故事从\"被区别对待→全镇体验聋人生活→重新认识\"，传递包容与换位思考的价值观。10题全靠情感线和逻辑链推理。<strong>备考启示→</strong>关注社会关怀类话题。"},
        {"title":"观察三 · D篇记叙文设\"态度变化\"题——Gavin从抗拒到热爱",
         "body":"Gavin从\"I don't even like ballet\"到\"When can I start?\"，Q35考态度变化是中考高频题型。<strong>备考启示→</strong>训练在记叙文中追踪人物态度转变。"},
        {"title":"观察四 · 语篇填空以旅行博客为载体——被动语态+词性转换双考",
         "body":"were greeted(被动)+happily(adj→adv)+colourful(n→adj)+left(过去时)+to explore(不定式)，10题覆盖核心语法。<strong>备考启示→</strong>词性转换双向(adj↔adv, n↔adj)需掌握。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(科技产品)</strong>：3分钟，价格/功能对比表格化</li><li><strong>B篇(睡眠)</strong>：每段一个要点，数据题直接定位</li><li><strong>C篇(绿角)</strong>：利→弊→对策结构清晰</li><li><strong>D篇(舞蹈)</strong>：按情感线\"抗拒→震撼→渴望\"做题</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=投稿信，要点=活动概况+参与过程+感受</li><li>时态=过去时为主，Dear Sir/Madam开头</li><li>描述1-2个具体才艺节目增加细节分</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(6题)：被动(were greeted)/adj→adv(happily)/名词复数(kinds)/n→adj(colourful)/过去时(left)/不定式(to explore)</li><li>无提示(4题)：but/the/one/to</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：沉默日故事按\"提议→实施→领悟\"主线</li><li>还原：Q40(倾听)最确定先做，再用First/Second排除</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q21-Q36)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q37-Q40)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q41-Q50)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q51-Q60)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q61-Q64)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q65)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 抚顺 ============
def fushun():
    return {
    "district": "抚顺",
    "exam_name": "抚顺市2026年初中学业水平模拟考试",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分），无听力。阅读理解20题40分占44.4%，加上阅读还原与阅读表达共58分，阅读能力占比<strong>64.4%</strong>。抚顺市统考卷，非沈阳区卷。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"水银温度计停产与额温枪科普","theme":"健康·科技","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("科普","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"数据提取","location":"about 1 gram→A"},
            {"no":"Q2","type":"细节理解","ability":"因果关系","location":"mercury is dangerous→C"},
            {"no":"Q3","type":"细节理解","ability":"注意事项","location":"not cover forehead with hair→C"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"health topic→Health News→A"},
         ]},
        {"id":"B","genre":"记叙文","topic":"Dra守护玛旁雍错湖湿地十年","theme":"生态保护·中国","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("环保","green"),("中国故事","purple")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"物品提取","location":"life-saving bag: food and water→C"},
            {"no":"Q6","type":"细节理解","ability":"职责归纳","location":"patrol+deal with danger→A"},
            {"no":"Q7","type":"代词指代","ability":"指代推断","location":"it=the eagle(上文受伤的鹰)→B"},
            {"no":"Q8","type":"标题选择","ability":"主旨概括","location":"A Protector of the Wetland→D"},
         ]},
        {"id":"C","genre":"记叙文","topic":"卷发女孩的自我接纳之路","theme":"个人成长·自信","difficulty":"★★☆","cls":"success",
         "tags":[("记叙文","orange"),("成长","purple"),("自信","green")],
         "questions":[
            {"no":"Q9","type":"细节理解","ability":"外貌描述","location":"short and curly→B"},
            {"no":"Q10","type":"细节理解","ability":"因果关系","location":"wanted to fit in and be accepted→C"},
            {"no":"Q11","type":"推理判断","ability":"性格推断","location":"confident and true to herself→B"},
            {"no":"Q12","type":"主旨大意","ability":"中心思想","location":"changes in her thinking→A"},
         ]},
        {"id":"D","genre":"说明文","topic":"Pipebots微型管道检测机器人","theme":"科技创新·城市","difficulty":"★★★","cls":"warning",
         "tags":[("说明文","blue"),("科技","orange"),("城市","green")],
         "questions":[
            {"no":"Q13","type":"细节理解","ability":"因果关系","location":"old pipes under streets leak→B"},
            {"no":"Q14","type":"词义猜测","ability":"上下文推断","location":"crawl=move slowly→A"},
            {"no":"Q15","type":"段落大意","ability":"段落归纳","location":"How Pipebots work and help→D"},
            {"no":"Q16","type":"写作目的","ability":"作者意图","location":"introduce an invention→D"},
         ]},
    ],
    "restore": {
        "topic": "积极思维的力量——什么是正面思考",
        "structure": "引出话题→定义→重要性→困难时期→如何培养",
        "slots": [
            ("17","段尾","前文look on the bright side→a simple example","B"),
            ("18","段首","后文spend time thinking about what you want→定义正面思考","A"),
            ("19","段中","前文brain can't deal with everything→So choose what to focus on","D"),
            ("20","段首","后文start by paying attention→How can you develop it","E"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "Alan的养鸡梦——想养一百万只鸡的男孩",
        "emotion_line": "梦想当农民→热爱鸡→50只鸡→Nugget最爱→卖蛋攒钱→梦想自己的农场",
        "theme": "热爱是最好的老师——小男孩的农场梦",
        "questions": [
            {"no":"Q21","type":"语境推理","pos":"名词","answer":"B. farmer","clue":"super farmer raise chickens"},
            {"no":"Q22","type":"语境推理","pos":"名词","answer":"C. kids","clue":"most kids love toys"},
            {"no":"Q23","type":"语境推理","pos":"动词","answer":"A. feeds","clue":"feeds about 50 chickens"},
            {"no":"Q24","type":"语境推理","pos":"名词","answer":"D. hen","clue":"favorite hen Nugget"},
            {"no":"Q25","type":"语境推理","pos":"形容词","answer":"B. biggest","clue":"biggest chicken lay most eggs"},
            {"no":"Q26","type":"语境推理","pos":"动词","answer":"C. learned","clue":"learned that chickens lived in poor conditions"},
            {"no":"Q27","type":"固定搭配","pos":"动词短语","answer":"B. started with","clue":"started with five chickens"},
            {"no":"Q28","type":"语境推理","pos":"副词","answer":"A. quickly","clue":"number quickly grew"},
            {"no":"Q29","type":"语境推理","pos":"动词","answer":"C. build","clue":"build a chicken fortress"},
            {"no":"Q30","type":"语境推理","pos":"名词","answer":"D. uniform","clue":"changing into school uniform"},
        ],
        "word_types": [("名词","4","40%"),("动词/动词短语","3","30%"),("形容词","1","10%"),("副词","2","20%")],
    },
    "grammar_topic": "国际太极拳日——太极拳从中国走向世界",
    "grammar_theme": "传统文化·健康",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to improve","clue":"celebrate to improve health"},
        {"no":"Q32","type":"无提示·虚词","point":"冠词","answer":"an","clue":"an excellent master"},
        {"no":"Q33","type":"无提示·虚词","point":"介词","answer":"from","clue":"from China to the world"},
        {"no":"Q34","type":"有提示·词形变化","point":"被动语态","answer":"is shared","clue":"which is shared by people"},
        {"no":"Q35","type":"有提示·词形变化","point":"最高级","answer":"most popular","clue":"one of the most popular"},
        {"no":"Q36","type":"有提示·词形变化","point":"名词复数","answer":"years","clue":"for many years"},
        {"no":"Q37","type":"有提示·词形变化","point":"一般过去时","answer":"thought","clue":"I thought it was for old people"},
        {"no":"Q38","type":"无提示·虚词","point":"连词","answer":"and","clue":"both slow and convenient"},
        {"no":"Q39","type":"有提示·词形变化","point":"现在完成时","answer":"has become","clue":"So far, has become"},
        {"no":"Q40","type":"有提示·词形变化","point":"代词所有格","answer":"its","clue":"Through its slow movements"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("现在完成时","1","高"),("一般过去时","1","高"),
        ("最高级","1","高"),("名词复数","1","高"),
        ("非谓语(to do)","1","中"),("代词所有格","1","中"),
        ("冠词(an)","1","中"),("连词(and)","1","中"),("介词(from)","1","中"),
    ],
    "reading_expr_topic": "AI让旅行更智能——数字导游的力量",
    "reading_expr_genre": "说明文",
    "reading_expr_tone": "科技·实用",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"How quickly did the AI app create Beni's travel plan?","answer":"Within seconds."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"What does Henry think of AI during his trip?","answer":"It can help him so much. / Helpful."},
        {"no":"Q43","score":"2分","type":"细节提取","question":"In Taiyuan, what did the student do with the AI app?","answer":"She used the AI app to recognize the palace/old building."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Will you prefer to use an AI guide or a human guide? Why? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"解说词","topic":"欢迎英国游学学生参观校园","genre":"解说词/演讲稿","word_count":"80-100",
        "requirements":["表示欢迎","介绍学校","表达美好祝愿"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q3,Q5,Q6,Q9,Q10,Q13","8","16分"),
        ("推理判断(Inference)","Q11","1","2分"),("主旨大意(Main Idea)","Q12","1","2分"),
        ("词义猜测(Word Meaning)","Q14","1","2分"),("标题选择(Best Title)","Q8","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("代词指代(Reference)","Q7","1","2分"),
        ("段落大意(Paragraph)","Q15","1","2分"),("写作目的(Purpose)","Q16","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","水银温度计与额温枪","健康·科技"),("B篇·阅读选择","守护玛旁雍错湖湿地","生态保护·中国"),
        ("C篇·阅读选择","卷发女孩的自我接纳","个人成长·自信"),("D篇·阅读选择","Pipebots管道检测机器人","科技创新·城市"),
        ("阅读还原","积极思维的力量","心理健康·成长"),("完形填空","养鸡男孩Alan的农场梦","梦想·坚持"),
        ("语篇填空","国际太极拳日","传统文化·健康"),("阅读与表达","AI数字导游","科技·旅行"),
        ("书面表达","欢迎英国学生参观校园","跨文化交际·校园"),
    ],
    "dna": [
        {"title":"观察一 · 中国元素双线并行——西藏湿地保护+太极拳国际化",
         "body":"B篇Dra守护玛旁雍错湖讲述中国生态故事，语篇填空太极拳话题展现传统文化国际化。<strong>备考启示→</strong>积累生态保护和传统文化双领域词汇。"},
        {"title":"观察二 · 科技话题现代感强——管道机器人+AI导游",
         "body":"D篇Pipebots微型管道机器人和阅读表达AI数字导游，科技创新类占比突出。Q14考crawl词义猜测，Q15考段落大意。<strong>备考启示→</strong>科技说明文中的生词往往可通过上下文推断。"},
        {"title":"观察三 · 完形填空选材独特——小男孩的养鸡梦",
         "body":"Alan养鸡故事温暖有趣，从\"5只→50只→梦想一百万只\"展现纯真梦想。名词题占40%，需结合农场场景推理。<strong>备考启示→</strong>生活场景类完形需积累日常词汇。"},
        {"title":"观察四 · 语篇填空考查现在完成时——has become是高频考点",
         "body":"太极拳话题涵盖to improve(不定式)/is shared(被动)/most popular(最高级)/has become(完成时)/its(所有格)，语法覆盖全面。<strong>备考启示→</strong>\"So far+现在完成时\"是常见搭配。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(科普)</strong>：图文结合，1 gram/dangerous直接定位</li><li><strong>B篇(湿地)</strong>：按段落找\"携带物品/职责/救援案例\"</li><li><strong>C篇(成长)</strong>：时间线\"小时候→10年级→后来\"</li><li><strong>D篇(机器人)</strong>：问题→方案→工作原理→前景</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=解说词，要点=欢迎+介绍学校+祝愿</li><li>开头Hello everyone! Welcome to...+结尾I hope...</li><li>介绍2-3个学校特色(图书馆/实验室/社团)</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(7题)：不定式/被动/最高级/复数/过去时/完成时/所有格</li><li>无提示(3题)：an/from/and，均为常见虚词</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：养鸡梦按\"梦想→行动→成长\"主线推进</li><li>还原：Q20(How can you develop it)最确定先做</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 营口 ============
def yingkou():
    return {
    "district": "营口",
    "exam_name": "2026年营口市初中学业水平考试第一次模拟考试",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分，考试时长90分钟），无听力。阅读理解20题40分占44.4%，加上阅读还原与阅读表达共58分，阅读能力占比<strong>64.4%</strong>。营口市统考卷，无单独答案文件，答案为推断。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"雪花的四种舞姿与天气预测","theme":"科学·天气","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("科普","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"图形识别","location":"spin=快速旋转→对应图标"},
            {"no":"Q2","type":"细节理解","ability":"信息匹配","location":"line or zigzag→rain or light snow→C"},
            {"no":"Q3","type":"主旨大意","ability":"目的归纳","location":"how to know weather by dances→D"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"science newspaper→D"},
         ]},
        {"id":"B","genre":"记叙文","topic":"选择坐在Mark身边——友善的力量","theme":"友谊·善良","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("友谊","green"),("善良","purple")],
         "questions":[
            {"no":"Q5","type":"代词指代","ability":"指代推断","location":"him=Mark→B"},
            {"no":"Q6","type":"推理判断","ability":"原因推断","location":"someone noticed and liked his work→D"},
            {"no":"Q7","type":"推理判断","ability":"情感变化排序","location":"lonely→agreeing to teach+giving drawing→C"},
            {"no":"Q8","type":"主旨大意","ability":"中心思想","location":"Showing kindness makes a big difference→B"},
         ]},
        {"id":"C","genre":"说明文","topic":"泰山外骨骼机器人——助力老年人登山","theme":"科技创新·养老","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("科技","orange"),("养老","green")],
         "questions":[
            {"no":"Q9","type":"词义猜测","ability":"上下文推断","location":"mobility-impaired=difficulty moving→C"},
            {"no":"Q10","type":"细节理解","ability":"功能归纳","location":"reduce tiredness→lower tiredness in legs→C"},
            {"no":"Q11","type":"推理判断","ability":"写作手法","location":"cable car limits view→describe advantage→D"},
            {"no":"Q12","type":"推理判断","ability":"未来趋势","location":"common in elderly care and daily life→D"},
         ]},
        {"id":"D","genre":"说明文","topic":"《百骏图》——中西绘画艺术的交汇","theme":"传统文化·艺术","difficulty":"★★★","cls":"warning",
         "tags":[("说明文","blue"),("传统文化","purple"),("艺术","orange")],
         "questions":[
            {"no":"Q13","type":"细节理解","ability":"人物信息","location":"invited to palace for painting skills→B"},
            {"no":"Q14","type":"细节理解","ability":"因果关系","location":"wonderful mix of two cultures→C"},
            {"no":"Q15","type":"篇章结构","ability":"结构分析","location":"Painting>Painter-Creation-Value→A"},
            {"no":"Q16","type":"标题选择","ability":"主旨概括","location":"One Hundred Horses: Where East Meets West→A"},
         ]},
    ],
    "restore": {
        "topic": "驯鹿边吃边睡的秘密——反刍与睡眠",
        "structure": "引出话题→反刍能力→科学研究→研究结论",
        "slots": [
            ("17","段首","前文wished you could solve both→talented deer gives answer","E"),
            ("18","段尾","前文rumination→helps break down and take in plants","A"),
            ("19","段首","后文fitted reindeer with tools→To find out secrets, scientists researched","B"),
            ("20","段中","前文kept awake→After ruminating, did not need much sleep","D"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "和失明爷爷在一起的夏天",
        "emotion_line": "期待暑假→爷爷失明但自强→开店经营→做家务→帮助他人→教会我人生道理",
        "theme": "一个失明老人从不说I can't——永远不要轻言放弃",
        "questions": [
            {"no":"Q21","type":"固定搭配","pos":"动词短语","answer":"A. spending","clue":"looked forward to spending"},
            {"no":"Q22","type":"语境推理","pos":"副词","answer":"B. never","clue":"it never slowed down"},
            {"no":"Q23","type":"语境推理","pos":"名词","answer":"B. shop","clue":"worked in a shop, return change"},
            {"no":"Q24","type":"语境推理","pos":"形容词","answer":"D. right","clue":"return the right change"},
            {"no":"Q25","type":"语境推理","pos":"动词","answer":"A. hand","clue":"hand customers their drinks"},
            {"no":"Q26","type":"语境推理","pos":"动词短语","answer":"D. move around","clue":"move around the house room to room"},
            {"no":"Q27","type":"语境推理","pos":"形容词","answer":"A. surprised","clue":"surprised at how he walked"},
            {"no":"Q28","type":"语境推理","pos":"副词","answer":"C. carefully","clue":"listened carefully and cheered them up"},
            {"no":"Q29","type":"语境推理","pos":"名词","answer":"D. memories","clue":"taught me memories I still treasure"},
            {"no":"Q30","type":"语境推理","pos":"动词","answer":"B. miss","clue":"I miss all moments"},
        ],
        "word_types": [("动词/动词短语","3","30%"),("名词","2","20%"),("形容词","3","30%"),("副词","2","20%")],
    },
    "grammar_topic": "宁忠岩米兰冬奥会夺金——中国速滑历史性突破",
    "grammar_theme": "体育·梦想",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"词性转换(v→n)","answer":"achievement","clue":"great achievement"},
        {"no":"Q32","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"easily","clue":"Success never comes easily"},
        {"no":"Q33","type":"有提示·词形变化","point":"序数词","answer":"seventh","clue":"finished the seventh place"},
        {"no":"Q34","type":"无提示·虚词","point":"冠词","answer":"a","clue":"a high mountain"},
        {"no":"Q35","type":"有提示·词形变化","point":"反身代词","answer":"himself","clue":"told himself to stay patient"},
        {"no":"Q36","type":"无提示·虚词","point":"介词","answer":"in","clue":"in the end"},
        {"no":"Q37","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to trust","clue":"reminding myself to trust"},
        {"no":"Q38","type":"有提示·词形变化","point":"被动语态","answer":"was asked","clue":"When he was asked"},
        {"no":"Q39","type":"有提示·词形变化","point":"词性转换(v→adj)","answer":"thankful","clue":"happy and thankful"},
        {"no":"Q40","type":"无提示·虚词","point":"连词(因果)","answer":"because","clue":"because it proves"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("词性转换(v→n)","1","高"),("词性转换(adj→adv)","1","高"),
        ("序数词","1","高"),("词性转换(v→adj)","1","高"),
        ("非谓语(to do)","1","中"),("反身代词","1","中"),
        ("冠词(a)","1","中"),("介词(in the end)","1","中"),("连词(because)","1","中"),
    ],
    "reading_expr_topic": "如何写一部小说——四条黄金法则",
    "reading_expr_genre": "说明文",
    "reading_expr_tone": "实用·指导",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"How should writers deal with the theme of their story?","answer":"Never tell it directly. Let readers work it out on their own."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"What should writers focus on when they talk about the characters?","answer":"Focus on who they are inside, not how they look."},
        {"no":"Q43","score":"2分","type":"推理归纳","question":"What does 'rules are often there to be broken' mean?","answer":"It means writers can sometimes try new ways and not follow rules strictly."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Which of the four rules is the hardest to follow? Give your reason(s). (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"书信","topic":"回复Eric——校园低碳生活周建议","genre":"书信/邮件","word_count":"80-100",
        "requirements":["感谢信任","提出建议","祝愿活动成功"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q10,Q13,Q14","5","10分"),
        ("推理判断(Inference)","Q6,Q7,Q11,Q12","4","8分"),("主旨大意(Main Idea)","Q3,Q8","2","4分"),
        ("词义猜测(Word Meaning)","Q9","1","2分"),("标题选择(Best Title)","Q16","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("代词指代(Reference)","Q5","1","2分"),
        ("篇章结构(Structure)","Q15","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","雪花的舞姿与天气预测","科学·天气"),("B篇·阅读选择","选择坐在Mark身边","友谊·善良"),
        ("C篇·阅读选择","泰山外骨骼机器人","科技创新·养老"),("D篇·阅读选择","《百骏图》中西艺术交汇","传统文化·艺术"),
        ("阅读还原","驯鹿边吃边睡的秘密","科学·动物"),("完形填空","和失明爷爷在一起的夏天","亲情·自强"),
        ("语篇填空","宁忠岩冬奥夺金","体育·梦想"),("阅读与表达","如何写一部小说","写作技巧·指导"),
        ("书面表达","校园低碳生活周建议","环保·校园"),
    ],
    "dna": [
        {"title":"观察一 · 传统文化融合西方视角——《百骏图》中西合璧",
         "body":"D篇讲述意大利画家郎世宁为雍正帝创作《百骏图》的故事，Q15考篇章结构、Q16考标题选择，是典型的\"中国故事国际化\"选材。<strong>备考启示→</strong>积累中国传统艺术相关词汇。"},
        {"title":"观察二 · 完形填空亲情线索强——失明爷爷的自强人生",
         "body":"爷爷失明却经营商店、做家务、帮助他人，情感线从\"敬佩→跟随→领悟\"。Q29 memories(回忆)和Q30 miss(怀念)是点睛之笔。<strong>备考启示→</strong>亲情类完形注意结尾的升华。"},
        {"title":"观察三 · 语篇填空以冬奥夺金为载体——词性转换占30%",
         "body":"宁忠岩话题涵盖achievement(v→n)/easily(adj→adv)/thankful(v→adj)三个词性转换，加上序数词seventh、反身代词himself。<strong>备考启示→</strong>三类词性转换(v→n, adj→adv, v→adj)是必考点。"},
        {"title":"观察四 · 科技+养老新话题——外骨骼机器人进入中考视野",
         "body":"C篇泰山外骨骼机器人话题新颖，Q9考mobility-impaired词义猜测，Q11考写作手法(提及缆车的目的)。<strong>备考启示→</strong>科技说明文需掌握\"对比论证\"的识别。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(雪花科普)</strong>：图文结合，匹配四种舞姿特征</li><li><strong>B篇(友善)</strong>：追踪Mark的情感变化线</li><li><strong>C篇(机器人)</strong>：段落对应\"功能/优势/前景\"</li><li><strong>D篇(百骏图)</strong>：时间线1688→1715→1724→完成</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=回信，要点=感谢+建议+祝愿</li><li>低碳建议：骑车上学/节约用水/垃圾分类</li><li>时态=一般现在时+祈使句</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(7题)：v→n(achievement)/adj→adv(easily)/序数词(seventh)/反身代词(himself)/to do(to trust)/被动(was asked)/v→adj(thankful)</li><li>无提示(3题)：a/in/because</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：爷爷故事按\"敬佩→跟随→领悟\"主线</li><li>还原：Q19(科学家研究)最确定先做</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


# ============ 铁岭 ============
def tieling():
    return {
    "district": "铁岭",
    "exam_name": "2026年中学生能力训练·英语模拟练习(二)",
    "has_listening": True,
    "skeleton_note": "本卷为<strong>听力+笔试卷</strong>（75题120分，考试时间120分钟），听力30题30分+笔试45题90分。铁岭二模，听力含听句子/短对话/长对话/短文四部分。笔试阅读Q31-Q50共20题40分，阅读能力占笔试<strong>64.4%</strong>。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"社区老年中心志愿者招募","theme":"社会服务·志愿","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("志愿服务","blue")],
         "questions":[
            {"no":"Q31","type":"细节理解","ability":"职责提取","location":"Chat with elderly and listen→D"},
            {"no":"Q32","type":"细节理解","ability":"数据计算","location":"2 hours×2 days=4 hours→D"},
            {"no":"Q33","type":"细节理解","ability":"条件理解","location":"middle school student or above→15岁→A"},
            {"no":"Q34","type":"文体判断","ability":"文本来源","location":"volunteer wanted→newspaper→C"},
         ]},
        {"id":"B","genre":"记叙文","topic":"瘫痪女孩张俊丽——从画笔到小说的自强之路","theme":"自强不息·梦想","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("自强","purple"),("艺术","green")],
         "questions":[
            {"no":"Q35","type":"细节理解","ability":"人物关系","location":"she wanted to learn painting→herself→D"},
            {"no":"Q36","type":"细节理解","ability":"人物评价","location":"parents tried best to support→C"},
            {"no":"Q37","type":"细节理解","ability":"事件排序","location":"first drawing→oils→shop→auto→d-a-b-c→D"},
            {"no":"Q38","type":"主旨大意","ability":"启示","location":"Never give up on ourselves→C"},
         ]},
        {"id":"C","genre":"说明文","topic":"慢下来的智慧——从自然中学习放慢节奏","theme":"健康生活·心理","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("心理健康","green"),("生活方式","orange")],
         "questions":[
            {"no":"Q39","type":"写作手法","ability":"开头方式","location":"asking a question→A"},
            {"no":"Q40","type":"细节理解","ability":"观点提取","location":"notice more details→B"},
            {"no":"Q41","type":"段落大意","ability":"段落归纳","location":"Para 3=benefits of slowing down→A"},
            {"no":"Q42","type":"细节理解","ability":"建议提取","location":"pay attention to things around us→C"},
         ]},
        {"id":"D","genre":"说明文","topic":"平板支撑的好处——代谢/平衡/心理","theme":"健康·运动","difficulty":"★★☆","cls":"warning",
         "tags":[("说明文","blue"),("运动","green"),("健康","orange")],
         "questions":[
            {"no":"Q43","type":"推理判断","ability":"图表推断","location":"metabolic rate stays high→D"},
            {"no":"Q44","type":"细节理解","ability":"因果关系","location":"muscles are weak→C"},
            {"no":"Q45","type":"篇章结构","ability":"结构分析","location":"总分总→A"},
            {"no":"Q46","type":"标题选择","ability":"主旨概括","location":"Benefits and Encouragement→D"},
         ]},
    ],
    "restore": {
        "topic": "红旗渠——天河的奇迹",
        "structure": "引出红旗渠→决定修渠→艰苦施工→建成意义",
        "slots": [
            ("Q47","段首","前文River in the Sky, built by hand→Red Flag Canal is such a wonder","C"),
            ("Q48","段中","前文not enough water→Instead of giving up, decided to build canal","E"),
            ("Q49","段尾","前文climbed mountains, dug rocks→some people even lost their lives","A"),
            ("Q50","段尾","前文not just a canal→stands for Red Flag Canal Spirit","B"),
        ],
    },
    "cloze": {
        "genre": "议论文",
        "topic": "大城市里的孤独——友谊是最好的解药",
        "emotion_line": "城市热闹→却感到孤独→矛盾感→朋友是解药→珍惜友谊",
        "theme": "在人群中感到孤独时，朋友是最好的缓解",
        "questions": [
            {"no":"Q51","type":"语境推理","pos":"形容词","answer":"B. noisy","clue":"streets noisy with activity"},
            {"no":"Q52","type":"固定搭配","pos":"名词","answer":"C. corner","clue":"every corner of the planet"},
            {"no":"Q53","type":"逻辑连词","pos":"连词","answer":"C. but","clue":"surrounded but still feel alone"},
            {"no":"Q54","type":"固定搭配","pos":"动词短语","answer":"A. walk through","clue":"walk through a crowd"},
            {"no":"Q55","type":"固定搭配","pos":"动词短语","answer":"D. deal","clue":"deal with this feeling"},
            {"no":"Q56","type":"语境推理","pos":"形容词","answer":"A. first","clue":"first thing I do"},
            {"no":"Q57","type":"语境推理","pos":"动词","answer":"C. reply","clue":"friends always reply"},
            {"no":"Q58","type":"语境推理","pos":"副词","answer":"C. easily","clue":"loneliness comes so easily"},
            {"no":"Q59","type":"语境推理","pos":"代词","answer":"A. some","clue":"some of the hardest times"},
            {"no":"Q60","type":"语境推理","pos":"名词","answer":"C. friendship","clue":"develop your own friendship"},
        ],
        "word_types": [("动词/动词短语","2","20%"),("名词","2","20%"),("形容词","2","20%"),("副词","2","20%"),("连词","1","10%"),("代词","1","10%")],
    },
    "grammar_topic": "白露——中国二十四节气中的秋之信使",
    "grammar_theme": "传统文化·节气",
    "grammar": [
        {"no":"Q61","type":"无提示·虚词","point":"冠词","answer":"the","clue":"the fifteenth solar term特指"},
        {"no":"Q62","type":"无提示·虚词","point":"介词","answer":"from","clue":"from late summer to early autumn"},
        {"no":"Q63","type":"有提示·词形变化","point":"比较级","answer":"cooler","clue":"weather becomes cooler"},
        {"no":"Q64","type":"有提示·词形变化","point":"名词复数","answer":"leaves","clue":"tree leaves"},
        {"no":"Q65","type":"有提示·词形变化","point":"一般现在时","answer":"rises","clue":"When the sun rises"},
        {"no":"Q66","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"normally","clue":"normally sown"},
        {"no":"Q67","type":"有提示·词形变化","point":"被动语态","answer":"is picked","clue":"tea is picked at this time"},
        {"no":"Q68","type":"有提示·词形变化","point":"代词所有格","answer":"their","clue":"make their bodies stronger"},
        {"no":"Q69","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to take","clue":"reminds us to take care"},
        {"no":"Q70","type":"无提示·虚词","point":"连词(因果)","answer":"because","clue":"because they help"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("比较级","1","高"),("一般现在时","1","高"),
        ("名词复数","1","高"),("词性转换(adj→adv)","1","高"),
        ("非谓语(to do)","1","中"),("代词所有格","1","中"),
        ("冠词(the)","1","中"),("介词(from)","1","中"),("连词(because)","1","中"),
    ],
    "reading_expr_topic": "抗战胜利80周年纪念标识的意义",
    "reading_expr_genre": "说明文",
    "reading_expr_tone": "庄重·爱国",
    "reading_expression": [
        {"no":"Q71","score":"2分","type":"细节提取","question":"When was the special logo published?","answer":"On May 13, 2025."},
        {"no":"Q72","score":"2分","type":"细节提取","question":"List one thing in the logo and tell its meaning.","answer":"The Great Wall stands for the strength and bravery of the Chinese people."},
        {"no":"Q73","score":"2分","type":"细节提取","question":"What can we learn when we see the logo?","answer":"We can learn about the past/history."},
        {"no":"Q74","score":"4分","type":"开放性表达","question":"Why is it important for students to understand this logo? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"书信","topic":"回复Jack——自然公园一日游建议","genre":"书信/邮件","word_count":"80-100",
        "requirements":["接受邀请","提出建议","期望与祝愿"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q31,Q32,Q33,Q35,Q36,Q37,Q40,Q42,Q44","9","18分"),
        ("推理判断(Inference)","Q43","1","2分"),("主旨大意(Main Idea)","Q38","1","2分"),
        ("标题选择(Best Title)","Q46","1","2分"),("文体判断(Text Type)","Q34","1","2分"),
        ("段落大意(Paragraph)","Q41","1","2分"),("篇章结构(Structure)","Q45","1","2分"),
        ("写作手法(Technique)","Q39","1","2分"),
        ("逻辑衔接(Cohesion)","Q47-Q50","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","社区老年中心志愿者招募","社会服务·志愿"),("B篇·阅读选择","瘫痪女孩张俊丽的自强之路","自强不息·梦想"),
        ("C篇·阅读选择","慢下来的智慧","健康生活·心理"),("D篇·阅读选择","平板支撑的好处","健康·运动"),
        ("阅读还原","红旗渠——天河的奇迹","中国故事·精神"),("完形填空","大城市里的孤独与友谊","心理健康·友谊"),
        ("语篇填空","白露——二十四节气","传统文化·节气"),("阅读与表达","抗战胜利80周年纪念标识","爱国教育·历史"),
        ("书面表达","自然公园一日游建议","自然·社交"),
    ],
    "dna": [
        {"title":"观察一 · 传统文化双载体——白露节气+红旗渠精神",
         "body":"语篇填空以白露节气为载体考查语法，阅读还原以红旗渠奇迹展现中国精神。<strong>备考启示→</strong>积累二十四节气和中国精神相关词汇。"},
        {"title":"观察二 · 完形填空议论文——城市孤独感话题新颖",
         "body":"议论文体裁的完形较少见，\"surrounded but lonely\"的矛盾感是解题关键。Q53 but(转折)和Q55 deal with(固定搭配)是必得分点。<strong>备考启示→</strong>议论文完形需抓住论证逻辑。"},
        {"title":"观察三 · 阅读表达以爱国教育为主题——抗战80周年标识",
         "body":"五大元素(长城/橄榄枝/光芒/80/时间线)各有寓意，Q72要求列举+解释，考查信息筛选与表达能力。<strong>备考启示→</strong>爱国教育类阅读需掌握象征意义的表达。"},
        {"title":"观察四 · 健康运动话题双篇——慢生活+平板支撑",
         "body":"C篇和D篇分别从\"慢下来\"和\"平板支撑\"两个角度讨论健康，Q43图表推断题和Q45结构分析题是亮点。<strong>备考启示→</strong>健康话题需训练图表理解和篇章结构分析。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下28-34分（满分40分）","body":"<ul><li><strong>A篇(招募)</strong>：3分钟，Requirements/Benefits直接定位</li><li><strong>B篇(自强)</strong>：按时间线排列事件(first drawing→oils→shop→novel)</li><li><strong>C篇(慢生活)</strong>：每段一个benefits，Q39开头方式直接判断</li><li><strong>D篇(平板支撑)</strong>：代谢→平衡→心理三段式</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li>体裁=回信，要点=接受邀请+建议+期望</li><li>建议：穿运动鞋/带自制食物/涂防晒</li><li>时态=一般将来时为主</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li>有提示(7题)：比较级(cooler)/复数(leaves)/现在时(rises)/adj→adv(normally)/被动(is picked)/所有格(their)/to do(to take)</li><li>无提示(3题)：the/from/because</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li>完形：城市孤独感，Q53 but是关键转折词</li><li>还原：红旗渠Q50(精神象征)最确定先做</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q31-Q46)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q47-Q50)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q51-Q60)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q61-Q70)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q71-Q74)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q75)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}
