"""Data entries for English analysis pages – Dalian + Anshan."""


def dalian():
    return {
    "city": "大连",
    "district": "大连",
    "round": "一模",
    "exam_name": "2026年大连市初中学业水平考试模拟考试(一)",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分，考试时间90分钟），听力口语单独考试。第一部分选择题50分（阅读理解40分+完形填空10分），第二部分非选择题40分（语篇填空10分+阅读与表达10分+书面表达20分）。阅读理解20题40分占笔试44.4%，加上阅读与表达共50分，阅读能力占笔试<strong>55.6%</strong>。<strong>无答案卷</strong>，答案为推算。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"校园慈善捐赠活动(Hospital Charity Event)","theme":"校园生活·公益","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("海报","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"时间信息提取","location":"Donation Time: May 15th→A"},
            {"no":"Q2","type":"细节理解","ability":"物品清单","location":"toilet paper+soap+wipes+tissues=abcd→D"},
            {"no":"Q3","type":"细节理解","ability":"奖励规则","location":"Each package=one credit, 3 packages=3 credits→A"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"Join us! Small acts→school noticeboard→C"},
         ]},
        {"id":"B","genre":"说明文","topic":"NEO家用人形机器人","theme":"科技创新·生活","difficulty":"★★☆","cls":"",
         "tags":[("说明文","blue"),("科技","orange"),("机器人","green")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"用途判断","location":"first humanoid robot for home use→B"},
            {"no":"Q6","type":"细节理解","ability":"操作方式","location":"AI voice commands+app→D"},
            {"no":"Q7","type":"细节理解","ability":"特点辨析","location":"30kg light but lift 70kg→A(light but strong)"},
            {"no":"Q8","type":"写作目的","ability":"全文目的","location":"introduce NEO a housekeeper of the future→A"},
         ]},
        {"id":"C","genre":"记叙文","topic":"爸爸的泳池清洁生意与家庭篮球时光","theme":"家庭亲情·关怀","difficulty":"★★☆","cls":"success",
         "tags":[("记叙文","orange"),("亲情","purple"),("成长","green")],
         "questions":[
            {"no":"Q9","type":"细节理解","ability":"问题识别","location":"lost many customers, economic downturn→C"},
            {"no":"Q10","type":"细节理解","ability":"因果关系","location":"knowing how much he loved basketball→B"},
            {"no":"Q11","type":"情感判断","ability":"情感推断","location":"victory dance+smiled→D(Relaxed)"},
            {"no":"Q12","type":"主旨大意","ability":"中心思想","location":"Family care can cheer up people→B"},
         ]},
        {"id":"D","genre":"说明文","topic":"中国航天员洞穴训练——模拟太空环境","theme":"中国故事·航天","difficulty":"★★★","cls":"warning",
         "tags":[("说明文","blue"),("中国故事","purple"),("航天","green")],
         "questions":[
            {"no":"Q13","type":"段落大意","ability":"段落归纳","location":"caves similar to space in many ways→C(Reasons)"},
            {"no":"Q14","type":"词义猜测","ability":"上下文推断","location":"fuzzy=Unclear(记忆模糊)→A"},
            {"no":"Q15","type":"细节理解","ability":"对比分析","location":"support team got in the way as little as possible→B(less support)"},
            {"no":"Q16","type":"标题选择","ability":"主旨概括","location":"Cave training for flying high→C"},
         ]},
    ],
    "restore": {
        "topic": "匹克球(Pickleball)运动介绍",
        "structure": "引出话题→历史起源→运动混合特点→游戏规则→号召参与",
        "slots": [
            ("17","段首","后文Three dads invented in backyard→1965年历史","E"),
            ("18","段首","后文court like badminton, net like tennis→三种运动混合","D"),
            ("19","段中","前文serve underhand→Next is two-bounce rule","B"),
            ("20","段尾","前文Do you want to try it?→Take a paddle and find a court","A"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "迟到的代价(A little late? Big mistake!)——Raheel的教训",
        "emotion_line": "经常迟到→不以为意→影响友谊→参加歌唱比赛→因迟到被拒→领悟教训",
        "theme": "守时是一种重要的品质，迟到可能让你错失美好机会",
        "questions": [
            {"no":"Q21","type":"语境推理","pos":"副词","answer":"A. often","clue":"had a bad habit→often caused"},
            {"no":"Q22","type":"语境推理","pos":"名词","answer":"D. mistake","clue":"didn't think it was a mistake"},
            {"no":"Q23","type":"语境推理","pos":"名词","answer":"D. friendships","clue":"Being late influenced his friendships"},
            {"no":"Q24","type":"语境推理","pos":"动词","answer":"B. missed","clue":"showed up late and missed cake-cutting"},
            {"no":"Q25","type":"语境推理","pos":"形容词","answer":"B. disappointed","clue":"friend disappointed, stopped talking"},
            {"no":"Q26","type":"语境推理","pos":"动词","answer":"A. win","clue":"hoped he would win the competition"},
            {"no":"Q27","type":"语境推理","pos":"名词","answer":"C. confidence","clue":"full of confidence on competition day"},
            {"no":"Q28","type":"语境推理","pos":"动词","answer":"D. telling","clue":"kept telling his mom Just five more minutes"},
            {"no":"Q29","type":"语境推理","pos":"动词","answer":"B. enter","clue":"wasn't allowed to enter(迟到不准进场)"},
            {"no":"Q30","type":"语境推理","pos":"形容词","answer":"C. important","clue":"Being on time is really important"},
        ],
        "word_types": [("名词","3","30%"),("动词","3","30%"),("形容词","2","20%"),("副词","2","20%")],
    },
    "grammar_topic": "外卖简史——从汉代到宋代的外卖发展",
    "grammar_theme": "传统文化·生活",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"一般过去时","answer":"started","clue":"it started a long time ago"},
        {"no":"Q32","type":"有提示·词形变化","point":"被动语态","answer":"was used","clue":"food delivery was used in the Song Dynasty"},
        {"no":"Q33","type":"无提示·虚词","point":"冠词","answer":"a","clue":"a special way to serve"},
        {"no":"Q34","type":"有提示·词形变化","point":"名词复数","answer":"shops","clue":"from local shops"},
        {"no":"Q35","type":"有提示·词形变化","point":"比较级","answer":"harder","clue":"ordering was harder than today"},
        {"no":"Q36","type":"无提示·虚词","point":"连词(选择)","answer":"or","clue":"visit in person or send someone"},
        {"no":"Q37","type":"有提示·词形变化","point":"代词所有格","answer":"their","clue":"wanted their food to be warm"},
        {"no":"Q38","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"luckily","clue":"luckily they were very clever"},
        {"no":"Q39","type":"无提示·虚词","point":"介词","answer":"in","clue":"space in the middle"},
        {"no":"Q40","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to keep","clue":"pour hot water to keep food warm"},
    ],
    "grammar_stats": [
        ("一般过去时","1","高"),("被动语态","1","高"),("比较级","1","高"),
        ("词性转换(adj→adv)","1","高"),("名词复数","1","高"),
        ("非谓语(to do)","1","中"),("代词所有格","1","中"),
        ("冠词(a)","1","中"),("连词(or)","1","中"),("介词(in)","1","中"),
    ],
    "reading_expr_topic": "海豚的长寿秘密——友谊让你更年轻",
    "reading_expr_genre": "说明文",
    "reading_expr_tone": "科普·温馨",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"细节提取","question":"How do dolphins live?","answer":"They live in groups called pods."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"What surprising result did the scientists find?","answer":"Male dolphins with more close friends aged more slowly."},
        {"no":"Q43","score":"2分","type":"因果推理","question":"Why might friendship help dolphins?","answer":"Having close friends may lower stress. They feel relaxed instead of worried."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Do you agree with Mia's comment? Give an example from your own life. (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"书信","topic":"回复Henry——鼓励参加环保演讲比赛","genre":"书信/邮件","word_count":"80-100",
        "requirements":["理解他的感受","鼓励参赛并给出理由","表达美好祝愿"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q3,Q5,Q6,Q7,Q9,Q10,Q15","9","18分"),
        ("推理判断(Inference)","Q11","1","2分"),("主旨大意(Main Idea)","Q12","1","2分"),
        ("词义猜测(Word Meaning)","Q14","1","2分"),("标题选择(Best Title)","Q16","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("段落大意(Paragraph)","Q13","1","2分"),
        ("写作目的(Purpose)","Q8","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","校园慈善捐赠活动","校园生活·公益"),("B篇·阅读选择","NEO家用人形机器人","科技创新·生活"),
        ("C篇·阅读选择","爸爸的篮球时光","家庭亲情·关怀"),("D篇·阅读选择","中国航天员洞穴训练","中国故事·航天"),
        ("阅读还原","匹克球运动介绍","运动·健康"),("完形填空","迟到的代价——Raheel的教训","品质修养·守时"),
        ("语篇填空","外卖简史——从汉代到宋代","传统文化·生活"),("阅读与表达","海豚的长寿秘密——友谊","科学·友谊"),
        ("书面表达","鼓励参加环保演讲比赛","环保·鼓励"),
    ],
    "dna": [
        {"title":"观察一 · 中国故事双线并行——航天洞穴训练+外卖简史",
         "body":"D篇以重庆武隆洞穴为背景讲述中国航天员训练故事(Xinhua/CGTN/Beijing Daily)，语篇填空以汉代到宋代外卖发展为载体。<strong>\"中国故事+传统文化\"</strong>双线贯穿全卷。<strong>备考启示→</strong>积累航天和传统文化相关词汇(astronaut/cave/takeout/delivery)。"},
        {"title":"观察二 · 科技话题占比突出——NEO机器人+航天训练",
         "body":"B篇NEO人形机器人(1.6m/30kg/70kg负重/22分贝/$20,000)数据丰富，D篇航天训练信息量大(ESA对比/蒋元/朱阳柱引言)。<strong>数据型说明文</strong>需快速定位数字。<strong>备考启示→</strong>练习\"带着问题找数据→同义替换识别\"的阅读策略。"},
        {"title":"观察三 · 完形填空以时间线推进——从日常迟到到错失机会",
         "body":"Raheel故事从\"迟到习惯→影响友谊(Q23-Q25)→歌唱比赛被拒(Q26-Q29)→领悟教训(Q30)\"，10题全靠<strong>事件因果链</strong>推理。名词和动词各占30%，无形容词难题。<strong>备考启示→</strong>完形填空先通读把握故事主线，再逐空根据因果逻辑选择。"},
        {"title":"观察四 · 阅读与表达选材独特——海豚友谊与衰老速度",
         "body":"以澳大利亚鲨鱼湾宽吻海豚研究为素材，Q42考\"朋友多的海豚衰老更慢\"的核心发现。Q44要求结合Mia评论+自身生活举例。<strong>科普+开放题</strong>是中考英语阅读表达的主流模式。<strong>备考启示→</strong>准备\"科学发现→个人生活联系\"的答题模板。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下24-28分（满分32分）","body":"<ul><li><strong>A篇(慈善海报)</strong>：3分钟速读，时间/物品/奖励规则直接在文中定位</li><li><strong>B篇(NEO机器人)</strong>：每段一个特点(外形/功能/重量/噪音/价格)，按段落对应题目</li><li><strong>C篇(记叙文)</strong>：抓情感线\"担忧→打篮球→笑容→释然\"，Q12主旨题综合全文</li><li><strong>D篇(航天训练)</strong>：按段落编号②③④⑤⑥定位，Q14词义猜测回原句\"memory got fuzzy\"</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li><strong>审题三步</strong>：①体裁=回信 ②要点=理解感受+鼓励+祝愿 ③时态=一般现在时+祈使句</li><li><strong>本卷话题</strong>：环保演讲比赛，Henry担心不能获奖</li><li><strong>高分策略</strong>：鼓励话语+具体理由(learn a lot/make friends/improve speaking)，3段结构</li><li><strong>必备句型</strong>：I understand how you feel. / Don't worry about... / I believe you can...</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li><strong>有提示(7题)</strong>：过去时(started)/被动(was used)/复数(shops)/比较级(harder)/所有格(their)/adj→adv(luckily)/to do(to keep)</li><li><strong>无提示(3题)</strong>：a(special way)/or(选择)/in(the middle)</li><li><strong>必背规律</strong>：比较级标志词than / 被动语态be+done / pour...to do(目的)</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li><strong>完形(迟到)</strong>：通读把握\"坏习惯→代价→教训\"主线，Q22/Q30是关键(mistake/important)</li><li><strong>还原(匹克球)</strong>：Q18(三种运动混合)最确定先做，Q17/Q20首尾段定位</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}


def anshan():
    return {
    "city": "鞍山",
    "district": "鞍山",
    "round": "一模",
    "exam_name": "2026年全市初中九年级第一次质量调查",
    "has_listening": False,
    "skeleton_note": "本卷为<strong>纯笔试卷</strong>（45题90分，考试时间90分钟），听力口语单独考试。第一部分选择题50分（阅读理解40分+完形填空10分），第二部分非选择题40分（语篇填空10分+阅读与表达10分+书面表达20分）。阅读理解20题40分占笔试44.4%，加上阅读与表达共50分，阅读能力占笔试<strong>55.6%</strong>。<strong>含完整答案</strong>。",
    "passages": [
        {"id":"A","genre":"应用文","topic":"Haleiwa Island海岛旅游网页","theme":"日常生活·旅游","difficulty":"★☆☆","cls":"info",
         "tags":[("应用文","green"),("旅游","blue")],
         "questions":[
            {"no":"Q1","type":"细节理解","ability":"时间信息提取","location":"9 hours→B"},
            {"no":"Q2","type":"细节理解","ability":"活动内容","location":"FOOD·GAS·SHOPS·BEACHES→Shopping→A"},
            {"no":"Q3","type":"细节理解","ability":"费用计算","location":"$136×2+$136×50%=$340→D"},
            {"no":"Q4","type":"文体判断","ability":"文本来源","location":"10,379 likes+Plan with AI+Mobile ticket→website→B"},
         ]},
        {"id":"B","genre":"记叙文","topic":"小侦探Jack找到丢失的钻戒","theme":"推理侦探·智慧","difficulty":"★★☆","cls":"",
         "tags":[("记叙文","orange"),("侦探","purple"),("智慧","green")],
         "questions":[
            {"no":"Q5","type":"细节理解","ability":"因果关系","location":"water isn't good for ring→D"},
            {"no":"Q6","type":"词义猜测","ability":"上下文推断","location":"slippery=Smooth and easy to fall off→C"},
            {"no":"Q7","type":"细节理解","ability":"事件排序","location":"①-④-③-②→C"},
            {"no":"Q8","type":"标题选择","ability":"主旨概括","location":"A Wise Case Solver→B"},
         ]},
        {"id":"C","genre":"说明文","topic":"中国传统音乐的传承与创新","theme":"传统文化·音乐","difficulty":"★★☆","cls":"success",
         "tags":[("说明文","blue"),("传统文化","purple"),("音乐","green")],
         "questions":[
            {"no":"Q9","type":"细节理解","ability":"数量计算","location":"guzheng+suona+erhu+pipa=four→D"},
            {"no":"Q10","type":"细节理解","ability":"信息提取","location":"number of listeners is dropping→C"},
            {"no":"Q11","type":"细节理解","ability":"方法归纳","location":"mixes folk singing and operas with instruments→C"},
            {"no":"Q12","type":"推理判断","ability":"作者观点","location":"with creativity, great things happen→D"},
         ]},
        {"id":"D","genre":"说明文","topic":"木桶效应(Wooden Barrel Effect)","theme":"学习方法·哲理","difficulty":"★★★","cls":"warning",
         "tags":[("说明文","blue"),("哲理","orange"),("学习方法","green")],
         "questions":[
            {"no":"Q13","type":"细节理解","ability":"原理理解","location":"shortest piece decides water level→C"},
            {"no":"Q14","type":"写作手法","ability":"论证方式","location":"basketball team+student examples→A(举例)"},
            {"no":"Q15","type":"推理判断","ability":"观点推断","location":"tilt barrel→make good use of strengths→D"},
            {"no":"Q16","type":"篇章结构","ability":"结构分析","location":"①②/③④/⑤/⑥→D"},
         ]},
    ],
    "restore": {
        "topic": "课堂保持清醒的四种方法",
        "structure": "课堂参与→身体活跃→饮食饮品→具体建议",
        "slots": [
            ("17","段首","后文listen to teacher→积极参与课堂","E"),
            ("18","段中","前文Walk around→运动告诉身体不是睡觉时间","C"),
            ("19","段首(标题)","后文three regular meals→用饮食保持清醒","B"),
            ("20","段中","前文balanced meals→食物给你能量","D"),
        ],
    },
    "cloze": {
        "genre": "记叙文",
        "topic": "UNICEF志愿者的心路历程——微小力量也有价值",
        "emotion_line": "迫切想改变世界→工作琐碎失落→参与视频制作→与资深同事学习→领悟微小行动的价值",
        "theme": "每个人都在用自己的方式贡献力量，微小行动也有巨大价值",
        "questions": [
            {"no":"Q21","type":"逻辑连词","pos":"连词","answer":"B. But","clue":"想解决大问题→But工作琐碎(转折)"},
            {"no":"Q22","type":"固定搭配","pos":"动词短语","answer":"D. feel like","clue":"didn't feel like creating value"},
            {"no":"Q23","type":"语境推理","pos":"名词","answer":"A. video","clue":"后文the video was completed"},
            {"no":"Q24","type":"语境推理","pos":"连词","answer":"A. how","clue":"learned how they understood jobs"},
            {"no":"Q25","type":"固定搭配","pos":"动词","answer":"D. takes","clue":"making big change takes time"},
            {"no":"Q26","type":"语境推理","pos":"副词","answer":"D. always","clue":"time spent is always worth it"},
            {"no":"Q27","type":"语境推理","pos":"动词","answer":"C. begins","clue":"Once it begins, it can grow"},
            {"no":"Q28","type":"语境推理","pos":"形容词","answer":"A. valuable","clue":"even smallest thing can be valuable"},
            {"no":"Q29","type":"固定搭配","pos":"介词","answer":"B. In","clue":"In it(视频中)"},
            {"no":"Q30","type":"语境推理","pos":"名词","answer":"D. ways","clue":"helping in their own ways"},
        ],
        "word_types": [("名词","3","30%"),("动词/动词短语","2","20%"),("连词","2","20%"),("形容词","1","10%"),("副词","1","10%"),("介词","1","10%")],
    },
    "grammar_topic": "长征90周年——从江西到陕西的25000里",
    "grammar_theme": "历史·爱国教育",
    "grammar": [
        {"no":"Q31","type":"有提示·词形变化","point":"一般现在时(三单)","answer":"marks","clue":"This year marks the 90th anniversary"},
        {"no":"Q32","type":"无提示·虚词","point":"介词","answer":"from","clue":"started from Jiangxi"},
        {"no":"Q33","type":"有提示·词形变化","point":"代词所有格","answer":"our","clue":"our soldiers walked"},
        {"no":"Q34","type":"有提示·词形变化","point":"非谓语(to do)","answer":"to fight","clue":"spared no effort to fight"},
        {"no":"Q35","type":"无提示·虚词","point":"冠词","answer":"a","clue":"had a hard time creeping"},
        {"no":"Q36","type":"有提示·词形变化","point":"词性转换(n→adj)","answer":"snowy","clue":"snowy Jiajin Mountain"},
        {"no":"Q37","type":"无提示·虚词","point":"连词(因果)","answer":"so","clue":"didn't have enough food, so went hungry"},
        {"no":"Q38","type":"有提示·词形变化","point":"名词复数","answer":"lives","clue":"lost their lives"},
        {"no":"Q39","type":"有提示·词形变化","point":"被动语态","answer":"were left","clue":"only about 7,000 were left"},
        {"no":"Q40","type":"有提示·词形变化","point":"词性转换(adj→adv)","answer":"truly","clue":"truly understand the spirit"},
    ],
    "grammar_stats": [
        ("被动语态","1","高"),("一般现在时(三单)","1","高"),("名词复数","1","高"),
        ("词性转换(n→adj)","1","高"),("词性转换(adj→adv)","1","高"),
        ("非谓语(to do)","1","中"),("代词所有格","1","中"),
        ("冠词(a)","1","中"),("介词(from)","1","中"),("连词(so)","1","中"),
    ],
    "reading_expr_topic": "该不该对孩子撒谎——四种观点碰撞",
    "reading_expr_genre": "议论文",
    "reading_expr_tone": "思辨·教育",
    "reading_expression": [
        {"no":"Q41","score":"2分","type":"主旨提取","question":"What topic are they talking about?","answer":"Whether it is OK to lie to children."},
        {"no":"Q42","score":"2分","type":"细节提取","question":"Why is it necessary to tell children white lies according to Bay212?","answer":"Because it can make children feel good and keep them positive / ready to try again."},
        {"no":"Q43","score":"2分","type":"观点对比","question":"What opinion do Bernie and Missy have in common?","answer":"They both think that it is not good to lie to children."},
        {"no":"Q44","score":"4分","type":"开放性表达","question":"Whose opinion do you agree with? Why? (≥30词)","answer":"言之有理即可。"},
    ],
    "writing": {"type":"书信","topic":"回复Bill——分享初中生活关键词及故事","genre":"书信/邮件","word_count":"80-100",
        "requirements":["用一个词描述初中生活","讲述关于该关键词的故事","分享故事带给你的感悟"],"difficulty":"★★☆"},
    "reading_skills": [
        ("细节理解(Detail)","Q1,Q2,Q3,Q5,Q7,Q9,Q10,Q11,Q13","9","18分"),
        ("推理判断(Inference)","Q12,Q15","2","4分"),("主旨大意(Main Idea)","Q8","1","2分"),
        ("词义猜测(Word Meaning)","Q6","1","2分"),
        ("文体判断(Text Type)","Q4","1","2分"),("写作手法(Method)","Q14","1","2分"),
        ("篇章结构(Structure)","Q16","1","2分"),
        ("逻辑衔接(Cohesion)","Q17-Q20","4","8分(还原)"),
    ],
    "topics": [
        ("A篇·阅读选择","Haleiwa海岛旅游网页","日常生活·旅游"),("B篇·阅读选择","小侦探Jack找钻戒","推理侦探·智慧"),
        ("C篇·阅读选择","中国传统音乐的传承与创新","传统文化·音乐"),("D篇·阅读选择","木桶效应与个人成长","学习方法·哲理"),
        ("阅读还原","课堂保持清醒的方法","学习方法·健康"),("完形填空","UNICEF志愿者的心路历程","社会服务·价值"),
        ("语篇填空","长征90周年","历史·爱国教育"),("阅读与表达","该不该对孩子撒谎","教育·思辨"),
        ("书面表达","分享初中生活关键词","个人成长·回忆"),
    ],
    "dna": [
        {"title":"观察一 · 传统文化+爱国教育双主线——传统音乐+长征",
         "body":"C篇以古筝、唢呐、二胡、琵琶四大乐器引出传统音乐创新(VR技术+流行融合)，语篇填空以长征90周年为载体考查语法。<strong>\"传统文化+红色历史\"</strong>是鞍山卷最鲜明的选材特色。<strong>备考启示→</strong>积累传统乐器(guzheng/pipa/erhu)和长征(Long March/Red Army)相关词汇。"},
        {"title":"观察二 · 完形填空考查\"成长感悟\"——UNICEF志愿者体验",
         "body":"从\"迫切想改变世界→发现工作琐碎→参与视频制作→领悟微小价值\"，情感线从<strong>失望到顿悟</strong>。Q25 takes(固定搭配)和Q28 valuable(主旨词)是必得分点。<strong>备考启示→</strong>\"成长感悟\"类完形需抓住\"转折点\"(But/However/Later)。"},
        {"title":"观察三 · D篇说明文考篇章结构——木桶效应的论证层次",
         "body":"Q16考六段文章的结构划分(①②/③④/⑤/⑥)，这是<strong>辽宁中考英语的高频题型</strong>。定义→团队应用→个人应用→另一种思路→总结，层次清晰。<strong>备考启示→</strong>说明文按\"总→分→补→总\"结构划分段落。"},
        {"title":"观察四 · 阅读与表达以教育话题为载体——四种观点比较",
         "body":"Q43要求比较Bernie和Missy的共同观点，Q44要求选择一种观点并说明理由。这种<strong>多人观点比较+选择表态</strong>的题型需要精确信息提取+个人表达双能力。<strong>备考启示→</strong>准备\"我同意X的观点，因为...\"的答题框架。"},
    ],
    "strategy": [
        {"cls":"","title":"🎯 P0 · 阅读选择拿下24-28分（满分32分）","body":"<ul><li><strong>A篇(旅游网页)</strong>：3分钟速读，价格/时间/规则直接在图文中定位，Q3注意50% off计算</li><li><strong>B篇(侦探故事)</strong>：按时间线找\"丢戒指→调查→发现→解决\"，Q7排序题画时间线</li><li><strong>C篇(传统音乐)</strong>：每段一个创新方式(VR/混合/流行)，Q12推断题综合末段</li><li><strong>D篇(木桶效应)</strong>：先看Q16结构题→把握全文框架→再做Q13-Q15细节题</li></ul>"},
        {"cls":"warning","title":"⚡ P1 · 书面表达冲刺15-18分（满分20分）","body":"<ul><li><strong>审题三步</strong>：①体裁=回信 ②要点=关键词+故事+感悟 ③时态=回忆用过去时/感悟用现在时</li><li><strong>本卷话题</strong>：用一个词(unforgettable/growth/friendship)描述初中生活并讲故事</li><li><strong>高分模板</strong>：第1段关键词(2句) → 第2段故事(4-5句，有细节) → 第3段感悟(2句)</li><li><strong>必备句型</strong>：I still remember clearly that... / I felt so...that... / This experience taught me...</li></ul>"},
        {"cls":"success","title":"📌 P2 · 语篇填空稳拿7-9分（满分10分）","body":"<ul><li><strong>有提示(7题)</strong>：三单(marks)/所有格(our)/to do(to fight)/n→adj(snowy)/复数(lives)/被动(were left)/adj→adv(truly)</li><li><strong>无提示(3题)</strong>：from(start from)/a(had a hard time)/so(因果)</li><li><strong>必背规律</strong>：spare no effort to do / had a hard time doing / start from</li></ul>"},
        {"cls":"info","title":"🧩 P3 · 完形+还原拿下13-16分（满分18分）","body":"<ul><li><strong>完形(志愿者)</strong>：紧扣\"失望→制作视频→领悟价值\"主线，Q21 But是全文转折标志</li><li><strong>还原(保持清醒)</strong>：Q19是段落标题(Staying awake with food)最确定先做，再做Q17/Q18</li></ul>"},
    ],
    "target_rows": """<tr><td>阅读选择(Q1-Q16)</td><td>32分</td><td>22分</td><td>28分</td></tr>
<tr><td>阅读还原(Q17-Q20)</td><td>8分</td><td>4分</td><td>8分</td></tr>
<tr><td>完形填空(Q21-Q30)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>语篇填空(Q31-Q40)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>阅读与表达(Q41-Q44)</td><td>10分</td><td>7分</td><td>9分</td></tr>
<tr><td>书面表达(Q45)</td><td>20分</td><td>14分</td><td>18分</td></tr>""",
    "target_low": "61分(68%)",
    "target_high": "81分(90%)",
}
